### ISSUE TITLE
Bundler and Ruby versions specified in the Gemfile are not respected

### ISSUE THREAD

**Issue by hegyi** [oss-review-toolkit/ort#1308]
Gemfile specifies the ruby version:

```ruby
ruby '2.5.3'
```

The same ruby version is also expressed in a .ruby-version file:
```
# .ruby-version file in project root
2.5.3
```

Gemfile.lock specifies the version of bundler:
```
BUNDLED WITH
  1.17.2
```

Running the scan results in anerror:
```
[ERROR]: Bundler - IOException: Running 'bundle install --path vendor/bundle' in 'SOME_PATH' failed with exit code 18:
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.5.1, but your Gemfile specified 2.5.3
```

Maybe using RVM or Rbenv with the gemset feature would be an option?

**Comment by sschuberth** [comment]
@hegyi, ORT's *Bundler* implementation has been [massively](https://github.com/oss-review-toolkit/ort/pull/3514) [changed](https://github.com/oss-review-toolkit/ort/pull/4595) since your report. As we're using JRuby programmatically now, I'm pretty sure the issue shouldn't occur anymore, thus I'm closing this. Please reopen if you still see this issue nonetheless.
