### ISSUE TITLE
Download only POMs, not JARs, when analyzing Maven projects

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2115]
As we are only interested in meta-data / dependency information in the analyzer step, there is no need to download (big) JARs and not doing so should result in significant performance results.

**Comment by sschuberth** [comment]
Maybe these examples could help achieving this:

https://github.com/apache/maven-resolver/blob/master/maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/GetDependencyHierarchy.java
https://github.com/apache/maven-resolver/blob/master/maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/GetDependencyTree.java

**Comment by sschuberth** [comment]
Maybe we could leverage [Kotlin 1.4's dependencies resolution API](https://kotlinlang.org/docs/reference/whatsnew14.html#new-dependencies-resolution-api) for this...

**Comment by oheger-bosch** [comment]
The download of jars happens when the Maven analyzer uses the Maven API to read the project pom and create a Maven project from it. At this level, the API does not offer a way to suppress downloads when dependencies are to be resolved (what is needed for the analyzer).

The underlying Aether library offers functionality to just resolve dependencies without downloading them. So one option could be to turn off the resolving of dependencies in the high level API and do the resolving manually with the Aether API, similar to what Maven's _ProjectBuilder_ does.  However, as Aether uses a different object model internally, there is a lot of non-trivial conversion code required for this. Duplicating the logic from Maven's project builder in this area is probably not the best option.

After some experiments, I found a way of mocking Maven to believe that binary artifacts are already present locally. This can be achieved by a custom _WorkspaceReader_ implementation. The reader simply reports arbitrary files for requested binary artifacts, while delegating to a real reader to resolve poms. To test whether this approach has no undesired side effects, I cleaned up my local Maven repository before starting an analyzer run. The processing of the project then caused a bunch of poms to be downloaded (for the actual dependencies, but also for some Maven plugins), but no binaries where loaded. Nevertheless, the analyzer result contained all the dependencies of the project. So this approach seems to be promising.

**Comment by sschuberth** [comment]
> Maybe we could leverage [Kotlin 1.4's dependencies resolution API](https://kotlinlang.org/docs/reference/whatsnew14.html#new-dependencies-resolution-api) for this...

For completeness, the code for this seems to be at https://github.com/JetBrains/kotlin/tree/1ac9b4c38fdf5de56203b49f23021468023fa979/libraries/scripting/dependencies-maven/src/kotlin/script/experimental/dependencies/maven.
