### ISSUE TITLE
External Scanner e.g. ClearlyDefined

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [oss-review-toolkit/ort#2254]
Allow the ORT scan step to outsource scanning to a scan provider like Clearly Defined instead of local scanning.

Acceptance Criteria:
- [ ] If no scan result can be retrieved from the scan storage backend, no local scan is triggered. Instead the scan is outsourced to a scan provider which runs scans asynchronously
- [ ] This is an addon feature to the scan result backend provider because the scan results should then be retrieved from the place where the external scan provider stores its results, e.g., Clearly Defined is used to trigger the scans, the results are also retrieved from Clearly Defined.
- [ ] Local caching of results should be possible to reduce the dependency of a connection to Clearly Defined.

**Comment by blaumeiser-at-bosch** [comment]
Another alternative would be to trigger scans in a compliance office, that would do the needful to get back with approved compliance information on the analyzed component release. So this should be a service interface and Clearly Defined only an implementation of this.

**Comment by mnonnenmacher** [comment]
Related to #2252.

**Comment by sschuberth** [comment]
I'm actually closing this in favor of only keeping #2252, because the concept of *explicitly* triggering a scan (and eventually blocking for the result) does not fit well to ClearlyDefined (which implicitly starts harvesting of a non-existing scan result is queried). Other eternal / remote scanners should be tracked separately, like we already do e.g. for FOSSID (see #3016).
