### ISSUE TITLE
Does ORT use a Locally set Android SDK

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#2560]
Does _ORT_ use the ANDROID_HOME variable pointing to a locally set Android SDK in any of it's process steps when analysing/scanning etc.  an android based project?

**Comment by sschuberth** [comment]
ORT itself does not directly make use of the `ANDROID_HOME` environment variable, but e.g. an analyzed Gradle build system for Android apps does (via the Android plugin for Gradle).

This can BTW easily be checked yourself by searching ORT's source code for the "ANDROID_HOME" string, and you'll quickly see that it's only used in one single place to print its value for debugging purposes.

In general, I recommend directing questions to the ORT Slack channel instead of using this issue tracker for support requests.

**Comment by CleanHit** [comment]
@sschuberth Thanks, didn't realise there was an ORT Slack channel.
