### ISSUE TITLE
could not get package information for the dependencies which have private repositories

### ISSUE THREAD

**Issue by maanasiDivekar** [oss-review-toolkit/ort#2794]
Hello Team,

I am getting error in ORT while scanning that, 'could not get package information for the dependencies' This error is for those who have the private repositories which can not be accessed by everyone. What is the solution in such a case? is there any configuration needed to be added in the curation file for the same?

**Comment by sschuberth** [comment]
Hi @maanasiDivekar, depending on whether the private repository is accessed via HTTP(S) or SSH, you either need to configure credentials via a standard `.netrc` file, or by running an SSH agent. Regarding the `.netrc` file, you can see e.g. from the [Jenkinsfile](https://github.com/oss-review-toolkit/ort/blob/d3178ffa1bfb303d7141b80beb067cc080ee4b48/Jenkinsfile#L181) how to write a username and password to it.

**Comment by maanasiDivekar** [comment]
> Hi @maanasiDivekar, depending on whether the private repository is accessed via HTTP(S) or SSH, you either need to configure credentials via a standard `.netrc` file, or by running an SSH agent. Regarding the `.netrc` file, you can see e.g. from the [Jenkinsfile](https://github.com/oss-review-toolkit/ort/blob/d3178ffa1bfb303d7141b80beb067cc080ee4b48/Jenkinsfile#L181) how to write a username and password to it.

How does it work for repositories which have HTTP and not HTTPS. I was trying to scan some open-source projects using ORT 
(Example: maven 3.6.3, spring-data-jdbc-1.0.11.RELEASE, terraform-master) but most of the time I got error as "com.here.ort.analyzer.managers.utils.MavenSupport - Unable to find 'org.apache.velocity:velocity:jar:sources:1.5' in any of [http://people.apache.org/repo/m2-snapshot-repository, https://repo.maven.apache.org/maven2]".

**Comment by sschuberth** [comment]
Let me try to clarify some possible misunderstandings here:

> How does it work for repositories which have HTTP and not HTTPS.

Authentication-wise, there's no difference between HTTP and HTTPS. If you are talking about a **source code** repository (like a Git repository), then authentication needs to be configured via `.netrc` as described above. However, if you are talking about an **artifact** repository (like Artifactory) where Maven retrieves dependencies from, then authentication needs to be configured via your `~/.m2/settings.xml` file.

> What needs to be done for such cases?

That said, your above errors *do not look like authentication errors*. It more looks like ORT could not download the source code of the dependencies because the package's meta-data does not tell where from to download ("No VCS URL provided", "No source artifact URL provided"). In that cause you need to manually fixup the incomplete meta-data with so-called [curations](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-curations-yml.md).

**Comment by maanasiDivekar** [comment]
Hello, @sschuberth  Thank you so much for the clarification. I did check for the curations file and I am able to add the required metadata. 
But, as I am scanning a few of the most commonly used open-source projects (like the spring framework)  via ORT,  the expectation is ORT to scan such projects without any need for any humans intervention.  Is there any alternative to do this process automated?

**Comment by sschuberth** [comment]
It's not possible to do this without human intervention if no one else has corrected that broken meta data before.

However, sharing such curations for broken meta data is exactly one of the purposes of the [ClearlyDefined](https://clearlydefined.io/) initiative, and ORT can leverage curations from ClearlyDefined if you pass the `--clearly-defined-curations` [option to the analyzer](https://github.com/oss-review-toolkit/ort/blob/81f0030df433b7998d9c0562c6370c4a5ad9407c/cli/src/main/kotlin/commands/AnalyzerCommand.kt#L96).

So, if a curation has been created *once* (either on ClearlyDefined, or in ORT's own format), then *all* future scans of that package will run through without human intervention.

**Comment by sschuberth** [comment]
@maanasiDivekar, has your question been answered, and can this issue be closed?
