### ISSUE TITLE
Allow to prefer source artifacts over source code from VCS

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2848]
BTW, can we have an option to try artifact source before vcs?

_Originally posted by @kneep in https://github.com/oss-review-toolkit/ort/issues/2846#issuecomment-655879046_

**Comment by sschuberth** [comment]
Currently, it is hard-coded to try downloading sources from VCS first, and then try a source artifact:

https://github.com/oss-review-toolkit/ort/blob/46a9ae9f730d132bd363bfa72c3d61fce630b2ea/downloader/src/main/kotlin/Downloader.kt#L124-L155

There could be an option to change the order.

**Comment by kneep** [comment]
Here in China, as you may all know, we have some network limitation. The public vcs repositories are hosted on various sites. Some of these sites are not accessible (e.g. sourceforge) while others have poor speed (e.g. Github, especially after evening). But generally artifacts repositories have reasonable speed here and are more predictable. So maybe it's better to have some flexibility on the priority of the source of source code.

**Comment by sschuberth** [comment]
Another problem that would get solved by this:

Suppose a Maven (binary) artifact has both a belonging sources artifact and a SCM / VCS location. Then the current implementation would scan the source code from the VCS, but the VCS typically contains test code for that dependency which is not part of the sources artifact. As test code often has very different detected licenses than the real product code, scanning the VCS results in potentially many irrelevant (but not false) findings that would need to be excluded by a [package configuration](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md), which is cumbersome. With that in mind it makes sense to focus as much as possible on the source code that makes up the binary, which means to prefer the sources artifact.

**Comment by fviernau** [comment]
I believe it makes sense to make this configurable. I could see the following use cases

1. only scan source artifact
2. only scan VCS
3. prefer source artifact, fallback to VCS
4. prefer VCS, fallback to source artifact
5. prefer cached, then fallback to VCS, then fallback to source artifact
6. prefer cached, then fallback to source artifact, then fallback to source artifact

I believe what we currently have implemented is #5.
I'd propose to make the behavior configurable.
I'd have a strong interrest in having one configuration option which mimics the exact current behavior.

**Comment by mnonnenmacher** [comment]
Both approaches have pros and cons so I think it's best to let the decide which strategy to use. Of the options Frank mentioned I think 3 and 4 can be ignored because they are basically 5 and 6 with disabled scan storage. I am also for making this configurable, but I'm undecided if 5 or 6 would be the better default. Trying to collect some of the pros and cons to get an overview:

- VCS often contains many irrelevant files, like tests or related projects which are built from the same repository. On the other hand there is no guarantee that the source artifact matches the binary artifact, relevant source files or license files could be missing.
- There is no guarantee that the binary artifact matches the VCS revision, because reproducible builds are not enforced by any package repository (at least to my knowledge). I have seen many NPM artifacts which seem to be built from private branches because the Git revision in the metadata does not exist in the repository.
- VCS allows to generate links to the source code in the reports, e.g. to the exact location of license findings. That is mostly impossible for source artifacts.

**Comment by MarcelBochtler** [comment]
@fviernau's use cases 5 and 6 were implemented in this PR: https://github.com/oss-review-toolkit/ort/pull/3736.
VCS was configured to be preferred to the sources artifact, because this was the default before. Cache always takes precedence.

Use cases 1-4 can be achieved by disabling he postgres cache. So can this be considered done?


One issue I see is that the cached data may be from a different origin. E.g. if the configuration was changed at a later point in time.
How should this be handled?

One way I see:
If cached data is from different origin, redownload from the preferred origin.
Issue with this approach: The preferred origin might fail and the fallback should then again be the cached data.
The redownload will be tried every time, resulting in worse performance.

@sschuberth, @mnonnenmacher, @fviernau what is your opinion how to handle this, or should it be handled at all?

**Comment by fviernau** [comment]
> Use cases 1-4 can be achieved by disabling he postgres cache. So can this be considered done?

I doubt disabling the cache can be considered an implementation of 1-4 because that'd be extremely slow.

**Comment by MarcelBochtler** [comment]
> I doubt disabling the cache can be considered an implementation of 1-4 because that'd be extremely slow.

I think then we do have a different understanding of use case 1-4.
The usage of cache is not mentioned there. So what would be the difference of just completely disabling it?

**Comment by fviernau** [comment]
> I think then we do have a different understanding of use case 1-4.
The usage of cache is not mentioned there. So what would be the difference of just completely disabling it?

Yes, our understanding is different. What I meant by case 3 (prefer source artifact, fallback to VCS) is:
if a source artifact is available, then the OrtResult would contain a source artifact scan, in particular even if the scan result storage contain only a VCS scan for that package.

**Comment by MarcelBochtler** [comment]
> Currently the state of the cache can affect which (VCS or source artifact) scan is used.

Yes, this is the issue I was talking about in https://github.com/oss-review-toolkit/ort/issues/2848#issuecomment-815504815
But I see issues with my proposed solution:

> One way I see:
If cached data is from different origin, redownload from the preferred origin.
Issue with this approach: The preferred origin might fail and the fallback should then again be the cached data.
The redownload will be tried every time, resulting in worse performance.

**Comment by sschuberth** [comment]
> The redownload will be tried every time, resulting in worse performance.

So how about if we then just accept all stored scan results, but sort them in order of the preferred origins?

**Comment by oheger-bosch** [comment]
I would also recommend that we should not try to be too clever. One could argue that the user is responsible for the content of the cache - undesired results in the cache could be removed. So if caching is enabled, the results found there should be used IMHO (maybe ordered as suggested by @sschuberth).

BTW: Are there any helper commands that allow an introspection or modification of the cache? These could be useful in this context.

**Comment by sschuberth** [comment]
> Are there any helper commands that allow an introspection or modification of the cache?

No, but adding some of these, e.g. to the `helper-cli`, indeed seems to be a good idea.

**Comment by sschuberth** [comment]
@mnonnenmacher and @fviernau, so WRT to the question how to deal with stored scan results when the preferred source origin has been (re-)configured, would you agree to what I wrote [above](https://github.com/oss-review-toolkit/ort/issues/2848#issuecomment-852221696), to "accept all stored scan results, but sort them in order of the preferred origins"?

**Comment by mnonnenmacher** [comment]
What would be the purpose of sorting them? Currently we accept all matching scan results for a package and add them to the result, but AFAIK the order in which they are added to the result is not relevant anywhere.

**Comment by sschuberth** [comment]
> Currently we accept all matching scan results for a package

The point is that "matching" here only means "by id". But with the feature to prefer a source origin, we additionally are about the provenance.

> the order in which they are added to the result is not relevant anywhere.

Exactly, the order might be any order. But if there are VCS and artifacts scan results for the same package in the storage, we need to ensure to get artifact results if the source origin was configured to prefer / only use artifacts.

**Comment by MarcelBochtler** [comment]
Notes from the call with @sschuberth and @mnonnenmacher:
We'll create a `helper-cli` command that offers the functionality to remove the cached result with the wrong `Provenance`.
