### ISSUE TITLE
Handling of BOM artifacts

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#2897]
As BOM artifacts neither have a source artifact location nor a VCS location they do cause scanner download error ORT issues. 
Further depending on the `evaluator rules implementation` these packages may trigger any amount of `rule violations`.

The only way these `issues / violations` can currently be addressed is by means of a `RuleViolationResolution` or `IssueResolution`. This however may require multiple such configuration entries per package and thus is sub-optimal in terms of maintainability.

Below are two proposals resulting from a discussion with @tsteenbe @mnonnenmacher:

**Use a package curation to assign a dummy source artifact**

Use a dummy artifact containing content which pleases all policy rules, and set it as source artifact via a curation.

**Add a boolean hasSourceCode attribute to ORT packages defaulting to true**

- That attribute could be set to false via a curation.
- Ort would need to be adjusted to not even try scanning such artifacts.
- The policy rules would need to skip rule execution based on that flag.

Note: The name `hasSourceCode` can probably be improved.

**Comment by sschuberth** [comment]
As discussed during the TSC meeting we should be able to imply look at a POM's `packaging` to let the analyzer determine whether there is no source code (other than the POM itself) and set the source artifact accordingly.

**Comment by fviernau** [comment]
I believe the `evaluator rules` should be able to conditionally skip execution for this kind of artifacts, e.g. BOMs. 
A rule which verifies that a given expected license is DETECTED in a LICENSE file in the root directory would still file if above proposed solution (setting the source artifact URL to the POM itself) was applied.

In order to implement that conditional rule execution, I believe it would be good to introduce above proposed boolean flag.
@sschuberth @mnonnenmacher @tsteenbe , do you agree?

**Comment by sschuberth** [comment]
I'm still unclear why we would need such a flag that can be accessed by the evaluator if we manage to avoid the download errors and the resulting scanner errors to begin with by treating the BOM file itself as the source artifact consistently. Could you please elaborate on that?

**Comment by fviernau** [comment]
> I'm still unclear why we would need such a flag that can be accessed by the evaluator if we manage to avoid the download errors and the resulting scanner errors to begin with by treating the BOM file itself as the source artifact consistently.

I gave an example above which is neither about download errors nor about scanner errors, but about `rule violations` - was that clear?

**Comment by sschuberth** [comment]
I guess you mean

> A rule which verifies that a given expected license is DETECTED in a LICENSE file in the root directory would still file if above proposed solution (setting the source artifact URL to the POM itself) was applied.

and after re-reading it I believe I got the point for your use-case of such a boolean flag.

Given we had that flag, would you still set the source artifact URL to the BOM file itself so its contents get scanned (which IMO can provide useful information, as sometimes the full license text is included e.g. in a Maven POM)?

**Comment by fviernau** [comment]
> I guess you mean ...

yes.

> Given we had that flag, would you still set the source artifact URL to the BOM file itself so its contents get scanned (which IMO can provide useful information, as sometimes the full license text is included e.g. in a Maven POM)?

First of all I believe this question can be answered completely in isolation from the boolean flag one, anyhow to answer it:
I'm not 100% sure if everybody would like to treat the detected licenses originating from a BOM file exactly the same way as 
detected licenses coming from either VCS or source artifact. In particular it's not clear if license applicability is exactly similar.
This is the main reason why I'd prefer to not scan the BOM. Further we had this fallback which scanned POM files, which has been removed again.

Regarding the boolean flag would you be fine introducing it, and if so what do you think about the name `hasSourceCode`?

**Comment by sschuberth** [comment]
> First of all I believe this question can be answered completely in isolation from the boolean flag one

IMO the questions are related as their answers might have an influence on the best naming of your flag.

> Further we had this fallback which scanned POM files, which has been removed again.

Correct, but IIRC it was removed for a completely different reason (I believe it was related to scan result caching, and is not relevant anymore, so we *could* reintroduce it).

> Regarding the boolean flag would you be fine introducing it

Yes, on a `Package` class level, correct (just to be sire I understood you right)?

> , and if so what do you think about the name `hasSourceCode`?

I think that name might confuse users regarding how it's related to the source artifact / VCS entry, e.g. if the latter are empty (due to incomplete meta-data which would require a curation which does not exist yet) but `hasSourceCode` is `true`.

So what about inverting the logic and naming the flag `isBomArtifact`, or maybe even more generically `isMetaDataOnly` / `hasMetaDataOnly`?

**Comment by sschuberth** [comment]
Then let's go for `isMetaDataOnly` as I'd like to keep the "Only" in there to emphasize it's not meta-data plus maybe something, but really *only* meta-data.

> Do you think the BOM should be scanned?

I'm undecided, both approaches have pros and cons. Not scanning it might miss something, but treating  a BOM as source code seems a bit unclean given our current meaning of a package's source artifact; (mis-)using a BOM as the source code would stretch that meaning a bit. Also, this special behavior would then need to be implemented consistently across all package managers. Which now leads me to the conclusion that we should probably *not* treat a BOM as source code in order to scan it.

**Comment by fviernau** [comment]
Great, I'm happy with this. Thanks for your input! I'll implement it accordingly.
