### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#2971]
Can you update the system requirements?
I want to know the minimum specification for the system.
ex) scancode system requirements : https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#system-requirements

**Comment by sschuberth** [comment]
Actually there's nothing to *update*, as we don't mention any system requirements at all yet :laughing: That's mostly because the requirements heavily depend on the size and type of the analyzed project(s), the configured scanner etc. which all are user dependent and we have no influence on. But we could of course mention some very basic system requirements like a JRE (starting with version 8, version 11 and 64-bit preferred) and maybe about 8G of memory.

**Comment by dd-jy** [comment]
I understood it. Thanks!

**Comment by sschuberth** [comment]
Let's keep this open as I still agree we can add what I wrote above also to the `README.md` basically.
