### ISSUE TITLE
The Cargo package manager should work with modern Cargo CLI

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3094]
Apparently the output of `cargo metadata` has changed slightly in more recent Cargo versions like 1.43.0 on Ubuntu 18.04, also see

https://github.com/oss-review-toolkit/ort/blob/efc19763f74628985520d6572261f6d358491be9/analyzer/src/funTest/kotlin/managers/CargoSubcrateTest.kt#L42

The issue seems to be with the `isProjectDependency()` logic and should be fixed so tests pass locally on modern Linux distributions.

**Comment by sschuberth** [comment]
Some experiments are in the `modern-cargo` branch: https://github.com/oss-review-toolkit/ort/commit/f9f79a3e164bacfe187aec47ecd9c5ce267be777

**Comment by KorSin** [comment]
I dug a bit into this topic and found out some interesting things. In the above mentioned test, the metadata of a `Cargo.toml` is analyzed. This file contains a path dependency called `integration`. Before cargo version `1.40.0`, the metadata output contained package information about the path dependency such as transitive dependencies. Starting with `1.40.0`, this information is not present anymore, but only the name of the path dependency. This is a problem, since it is in general not possible to recover the missing information, since the path leading to the path dependency is missing. However, the expected output in the test contains this missing information and thus fails.

Looking inside the cargo code, the reason is that only packages are shown in the output that have a `lib` target. The `integration`
package contains only a `bin` target by default. So, one way to fix the test would be to have a `lib` target in `integration`, see [this](https://doc.rust-lang.org/cargo/reference/cargo-targets.html). But I do not know whether this is the behavior we want to have.
