### ISSUE TITLE
only use the analyzer module

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#3173]
Hi, I want to only use the analyzer module.
Is it possible to use only analyzer without building all ort?
ORT analyzer module is really great tool because it supports various package managers and prints the accurate OSS information.
So we want to guide this analyzer module for dependency analyzer tool to software developers.

**Comment by sschuberth** [comment]
You can't really only build the analyzer in order to run it, as the analyzer is a sub-command of the overarching `ort` CLI. Think of it like the `git` CLI, which also do esnot allow to only build "git clone" without also getting "git commit", for example.

That said no one forces you to actually *run* any other sub-command than the analyzer.

**Comment by dd-jy** [comment]
Yes, I understood.
But the ort tool is a little heavy to distribute for each developers.

**Comment by sschuberth** [comment]
Of course, what you still could do is to use the analyzer library programmatically to write your own thin CLI for the analyzer only.
