### ISSUE TITLE
Migrate the Git implementation to pure JGit

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3281]
We currently [use](https://github.com/oss-review-toolkit/ort/blob/master/downloader/src/main/kotlin/vcs/Git.kt) a mix of Git CLI and JGit as [JGit does not support sparse checkouts](https://bugs.eclipse.org/bugs/show_bug.cgi?id=383772). However, [this post](https://www.eclipse.org/forums/index.php?t=msg&th=1094825&goto=1794275&#msg_1794275) seems to have an answer how to emulate sparse checkouts in pure JGit.

As a side note, we also have the idea to [get rid of the need for sparse checkouts altogether](https://github.com/oss-review-toolkit/ort/issues/2668) for any VCS implementation, but that requires significantly more work.

**Comment by MarcelBochtler** [comment]
The proposed solution using 
```kotlin
git.checkout()
    .setStartPoint(revision)
    .addPaths(pathsToCheckout)
    .call()
```
unfortunately doesn't work.

The issue with this approach is that `workingTree.getRevision()` won't work anymore, because the partial checkout does not actually checkout the git revision.
`workingTree.getRevision()` returns an empty String when using the above method.

Another considered idea was to delete the non-required files, but this would decrease the downloader performance significantly for large repositories.

Leaving the ticket open because ORT should still migrate to a pure JGit implementation as soon as JGit supports sparse-checkouts.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
