### ISSUE TITLE
Analyzer: Optimize handling of dependencies in multiple Gradle build variants

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3321]
When analyzing Android projects that make use of build variants and flavors ORT requires a large amount of memory.

I analyzed a project with 3 build types and 18 flavors. The flavors are only used for different configurations not dependencies.
ORT was crashing with an Java Heap Space exception after some time when running it with `JAVA_OPTS="-Xmx4g" ort --info --force-overwrite analyze -i $PWD -o $PWD/ort/analyzer`.

The largest object in the heap dump I took is an ArrayList with >1300 instances of `Scope`s.
Each `Scope` contains all dependency incl. the transitive dependencies.
When allowing an even bigger max Java Heap of 8 GiB the analysis succeeded and I got a ~500 MiB `analyzer-result.yml`.

The List of `Scope`s is build [here](https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Gradle.kt#L233-L239).

As the build variants contains many duplicated dependencies there might be a more efficient way to store the scopes which may also be used for serialization to remove duplicated dependencies from the result file.

Edit: When only analyzing a single build variant of this project, the ORT analyzer never exceeds 800 MiB heap memory.

**Comment by MarcelBochtler** [comment]
This issue can be reproduced by analyzing [Firefox Focus for Andorid](https://github.com/mozilla-mobile/focus-android/tree/v8.8.4) with ORT:
`JAVA_OPTS="-Xmx4g" ort --info -m gradle -i $PWD -o $PWD/ort/analyzer`

**Comment by Martin-Idel-SI** [comment]
I had a look at the result files - for a different project I found > 2 million lines of `id: "Maven:androidx.annotation:annotation:1.1.0"` so just by omitting this particular dependency the whole analyzer result would take up roughly 30% less space... There are a few other dependencies in the 100.000nds, so just identifying those and omitting them could probably cut file size to 1/10th or so. I'm going to assume this would also cut the Heap space used significantly.

However, I believe the real solution should be to completely flatten the tree. The file I looked at had 97 scopes with roughly the same dependencies - any dependency I saw occurred at least 97 times. 

### How to flatten the tree? 

Create a list, where every dependency gets added with its id + direct dependency ids (no transitive dependencies). Then just store the scopes with their direct dependencies. In my case, this would reduce the size of the result file by a lot, probably orders of magnitude.

### Problems?

This will increase computation time when reading the tree: You'll have to read a dependency, lookup its dependencies, read the dependencies and lookup their dependencies until no dependencies are present. The amount of actual projects used will probably be down to a couple of thousands in a sorted list, so the lookup should be fast enough, I guess.

Also, this will only work if every ID will only ever come with the same set of dependencies. I would hope that this is the case (what about optional dependencies?), but I don't know for sure.

### Ideas for implementation

I would probably change the `PackageReference` to contain a `SortedSet<Identifier>` instead of the recursive `SortedSet<PackageReference>`. To have the same functionality, we then need a `DependencyStore` containing a `SortedSet<PackageReference>` for lookup and saving new dependencies. This `DependencyStore` then has to be serialized to a new section in the `analyzer-result.yml` and be available (global singleton?) in every `PackageReference` object.

In addition, the Gradle implementation could then be tweaked to recursively call `parseDependency` less often - if the package is known, it will already have been added to the `DependencyStore` and therefore no recursive dependency parsing is necessary. This should improve performance and heap space usage.

How does that sound to you? Any other suggestions?

**Comment by oheger-bosch** [comment]
Great analysis, @Martin-Idel-SI. I fully agree that the main problem lies in the inefficient storage format, which repeats the (potentially huge) dependency trees for all scopes again and again.

I am experimenting with a slightly different approach than you propose. I try to keep the tree-like structure of the `PackageReference` objects, but share a set of dependency trees over all scopes. This is possible in the yaml serialization by not using the scopes as entry points into the dependency graph, but have a separate scope mapping which assigns the direct dependencies to the scopes. Based on this mapping, the original scope structure can then be re-constructed on deserialization with a single traversal of all dependency trees.

This approach requires as well that packages always have the same set of dependencies for a straight-forward implementation. Unfortunately, it seems that this assumption is not valid: The `GradleAndroidFunTest` class operates on a test project that includes an example library, and this library has different sets of dependencies in different scopes. I will therefore think about possibilities to detect differences in dependency trees and include trees with the same packages in the result if they are not equivalent. This will of course increase the complexity of the solution.

**Comment by sschuberth** [comment]
> Based on this mapping, the original scope structure can then be re-constructed on deserialization

But doesn't that mean that the in-memory representation stays the same, and also consumes just as much memory as before?

**Comment by oheger-bosch** [comment]
> But doesn't that mean that the in-memory representation stays the same, and also consumes just as much memory as before?

No, because the `PackageReference` objects are shared between the scopes. So each dependency occurs only once (ideally) in the shared dependency graph and is not repeated for all scopes.

**Comment by sschuberth** [comment]
> Also, this will only work if every ID will only ever come with the same set of dependencies. I would hope that this is the case (what about optional dependencies?), but I don't know for sure.

Actually, this is unfortunately not the case, e.g. due to version conflict resolution, whose outcome may depend on the position of the dependency in the transitive dependency tree (!); just consider Maven's "nearest" and Gradle's "latest" version conflict resolution strategies.

**Comment by oheger-bosch** [comment]
While #3502 improves the situation by optimizing the representation of Gradle dependencies in the ORT model, there is still a lot of memory wasted by the Gradle plugin implementation that collects the dependencies. Here a similar optimization should be applied.

**Comment by oheger-bosch** [comment]
The two PRs #3502 and #3506 together significantly reduce the memory usage of the Gradle analyzer. With both of them applied, I was able to process the Firefox [Focus for Andorid](https://github.com/mozilla-mobile/focus-android.git) project with a memory limit of 4 GB.

**Comment by sschuberth** [comment]
Both above mentioned PRs were merged.
