### ISSUE TITLE
Add functionality to handle license choices

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#3396]
It should be possible to select a license if a package is dual licensed.
This should be possible to do ORT instance globally (`~/.ort/config/licenseChoices.yml`) and project specific (`.ort.yml`).
Project specific configurations should override global configrations.

The logic how to select and replace SPDX OR clauses are already defined in these tests:
https://github.com/oss-review-toolkit/ort/blob/5b612747fc19b2ce9220b2340b7d7edaac3bf655/spdx-utils/src/test/kotlin/SpdxExpressionTest.kt#L288-L368

**Comment by sschuberth** [comment]
Just a remark, such a file should be called `license-choices.yml` (no camel-case but a dash), and we should probably also give it a though whether we could add license choices to the existing `license-classifications.yml` instead of adding yet another configuration file.

**Comment by mnonnenmacher** [comment]
Copied comment from Slack which contains info relevant for this topic:

I would separate the discussions about (1) for which scope license choices should be configurable and (2) how it should be implemented.

For (1) I believe we need (a) global license choices (e.g. in license-choices.yml), something like "Apache-2.0 OR MIT" always chose "Apache-2.0". The question is, should this also be applied to supexpressions automatically? (b) Per package license choices, because for some packages we might want to make a different choice. This should override global choices. This could be configured in curations.yml. (c) Per project license choices, because two different projects might want to make a different choice for the same library. This should be configurable in ort.yml and override (a) and (b). And maybe in ort.yml we also need to support global and per package choices to support all possible use cases.

If we really want to implement all these options depends on how important we think the different use-cases are.

(2) The logic that applies the license choice should be implemented in LicenseInfoResolver. The problem here is that the ResolvedLicenseInfo for a package does currently not provide an SPDX expression but simply a list of individual licenses as ResolvedLicense objects.

(a) The first step would be to find out if there is a license choice to be able to provide a resolved license expression that uses the correct AND and OR operators in ResolvedLicense. Because if the model does not provide the information if there is a license choice, it does not make sense to implement a way to configure license choices. For this we can check if the declared license contains a license choice, and we could implement support for license choices detected by ScanCode. At least I was told that ScanCode would provide such information in the latest versions, but I have never verified that myself. Otherwise we have to assume that all detected licenses are concatenated by AND.

(b) If we have solved (a) the implementation in LicenseInfoResolver should follow the principle to be completely transparent, that means the API must allow to check what the original SPDX expression was, which choices were applied, and what the resulting SPDX expression is.

**Comment by MarcelBochtler** [comment]
> The question is, should this also be applied to supexpressions automatically?

@mnonnenmacher It was my understanding that it should be applied to choices automatically. This was also covered in this test:
https://github.com/oss-review-toolkit/ort/blob/master/spdx-utils/src/test/kotlin/SpdxExpressionTest.kt#L388-L395

**Comment by MarcelBochtler** [comment]
> At least I was told that ScanCode would provide such information in the latest versions, but I have never verified that myself.

ScanCode 3.2.3 result for a file from [h2database](https://github.com/h2database/h2database) which is licensed under `MPL-2.0 OR EPL-2.0`:

```json
          "matched_rule": {
            "identifier": "mpl-2.0_or_epl-1.0_and_proprietary-license_2.RULE",
            "license_expression": "(mpl-2.0 OR epl-1.0) AND proprietary-license",
            "licenses": [
              "mpl-2.0",
              "epl-1.0",
              "proprietary-license"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 54,
            "matched_length": 11,
            "match_coverage": 20.37,
            "rule_relevance": 100
          }
```

**Comment by MarcelBochtler** [comment]
For the already discussed scope: Project specific for a specific package.

We have multiple possibilities to design the configuration model for the `.ort.yml`:

(1) This design allows the user to set the absolute desired result license.
```yml
- id: package-id
  given: (A OR B) AND C
  choice: A AND C
```

(2) This design allows the user to set a choice with an optional sub-expression. The desired result license would be computed. Several choices can be given.
```yml
- id: `package-id`
  given: (A OR B) AND C
  apply-choice:
  - choice: A
    sub-expression?: A OR B
```

(3) This design allows the user to EITHER set the desired result license or to set optional sub-expressions with corresponding choices or both.
```yml
- id: package-id
  given: (A OR B) AND C
  choice?: A AND C
  sub-expressions?:
  - expression: A OR B
    choice: A
```

Design (1) would not be possible when applying the license choice without a specific package and would therefore result in a different configuration model.
Design (2) and (3) allow the user to simply choose their desired sub-expressions and their choices without having to calculate the absolute resulting license themselves.

@fviernau, @mnonnenmacher, @sschuberth 
What is your preferred solution?

**Comment by neubs-bsi** [comment]
We looked at our use case again. When different `given` are provided (e.g. detected has two license findings for the same package with different `OR` expressions) we need to be able to handle that. This is not covered by any of the designs (1) to (3). A possible solutions would be: 

(4) The design allows for one package identifier to get several choices that can have sub-expressions. These choices can be applied to declared, detected and concluded, which can have different `given` license expressions. This design also allows to choose an "absolute" license for a `given` license expression, as can be seen in the second `given` choice in the example. 

```yml
- id: package-id
  choices: 
  - given: (A OR B) AND C
    choice: A
    sub-expressions?: A OR B
  - given: (A OR B) AND C
    choice: A AND C
  - given: (D OR F)
    choice: D
```

What do you think? 
@fviernau @sschuberth @mnonnenmacher

**Comment by MarcelBochtler** [comment]
Opened a PR for the suggestion by @neubs-bsi
