### ISSUE TITLE
Analyzer: Consider expanding the range of supported versions of Conan

### ISSUE THREAD

**Issue by pilvikala** [oss-review-toolkit/ort#3440]
The Analyzer requires a specific version of Conan (=1.18.0), but Conan recommends installation using pip which by default installs the latest version available. Is there a reason why that specific version of Conan is required by the Analyzer? If not, can you consider making the Conan version greater than 1.18.0?

**Comment by sschuberth** [comment]
Historically, we were conservative in our version requirements for external tools and more or less only allowed those versions for which we had done the initial implementation against. But maybe it's time to drop these version checks altogether, and instead of getting issues to support never versions, see whether we get issues if a never versions breaks something. What do you think @mnonnenmacher @fviernau?

**Comment by mnonnenmacher** [comment]
I would not drop the version checks, because for some package managers we have minimum version requirements. Instead I would suggest that we remove the upper bound from the version ranges for all package managers. This allows to quickly set an upper bound if we know there is an issue which cannot immediately be fixed.
