### ISSUE TITLE
Move hard-coded defaults to `default.conf`

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3522]
Yes, because so far there are either no defaults for the config options or they have not been moved to this file.
Putting them in both places means to places to maintain so I'd prefer just one of them, but we could keep the defaults here for now and then make a separate change to move all defaults to `default.conf` later.

_Originally posted by @mnonnenmacher in https://github.com/oss-review-toolkit/ort/pull/3510#r561082591_

**Comment by fviernau** [comment]
Another option would be to have the defaults in the Kotlin code (configuration) and generate a 'default.conf' from it if that file is actually needed. This would ensure that ORT does actually have a reasonable default behavior without requiring the user to copy and paste the default configuration. Further it would be fully supported by the IDE including refactoring. Also constants defined in Kotlin code can be re-used. Also, for the user it might be simpler to revert parts of the configuration back to default, because its simpler to delete a line compared to finding the line in the default config and copy pasting it. Finally the user would remain up to date with default values automatically.

...just as an idea to consider

**Comment by oheger-bosch** [comment]
As `default.conf` is part of the ORT binary and the file is automatically included as a configuration source when constructing the global `OrtConfiguration`, the values contained in this file are always available.

This approach is quite similar to the approach taken by the [Lightbend Config library](https://github.com/lightbend/config). In the section about [defaults](https://github.com/lightbend/config#how-to-handle-defaults), they state that the API of the library does not support passing default values for missing configuration properties from application code. The philosophy is rather to have a reference configuration file (that corresponds to `default.conf` in our case) with defaults for all supported properties, and an application configuration (`ort.conf`), in which the user can override values that should be different from defaults.

**Comment by oheger-bosch** [comment]
While looking into this, I spotted a problem with the default value for the `commandLineNonConfig` property: It is defined as `"--processes", max(1, Runtime.getRuntime().availableProcessors() - 1).toString()`, so it contains a dynamic computation. How can we deal with this?

There are multiple options:
* Place a hard-coded value for the number of processes into `default.conf`.
* Do not place this property into `default.conf`, but have the value in Kotlin code.
* Introduce a placeholder, which is evaluated when reading the configuration. (This is a bit messy because there is already a mechanism to resolve environment variables; unfortunately, there is no portable environment variable for the number of processors we could use.)
* ?

@sschuberth @fviernau @mnonnenmacher, what are your preferences?

**Comment by fviernau** [comment]
I propose again to make the default values thing a Kotlin class and generate and autogenerate a yaml from it.

**Comment by oheger-bosch** [comment]
I think I do not fully understand your proposal to auto-generate the default.conf, @fviernau. When and how should this generation happen? And when the default values are in the code anyway, what is the point of having another default.conf file?

**Comment by fviernau** [comment]
> And when the default values are in the code anyway, what is the point of having another default.conf file?

Probably this is a misunderstanding. I assumed that we do not want to put default values in both places: (1) kotlin code and (2) default.conf, but only exactly in one of the two.

My idea was basically to somewhere in Kotlin define a variable like

```
const val ORT_DEFAULT_CONFIG = OrtConfiguration(
   ...
)
```
Then we could either (1) have a command line command which creates a file containing the default configuration or (2) let ORT create that default configuration automatically if it does not exist.

> what is the point of having another default.conf file?

I didn't mean to propose to have 2 default.conf files, but only zero.

**Comment by oheger-bosch** [comment]
I still don't get why a default.conf should be generated when the default values are already present in ORT. The file does not need to be present on the file system as it is never edited by the user. The user places custom configuration in the ort.conf file, but this configuration can be incomplete. For missing settings, the default values are taken into account; and these defaults could either be hard-coded in the ORT code or be placed in a default.conf file that is contained in the ORT binary.

**Comment by fviernau** [comment]
Hm, I tried to argue about whether putting the default values into "default.conf" is a good idea.
In my opinion putting ALL default values into Kotlin code is superior to putting them into a "default.conf" file.
That's basically all (the whole topic I wanted to bring up).

Does this make sense now?

**Comment by oheger-bosch** [comment]
Yes, okay. I was just confused because of the auto-generation part. Thanks.

**Comment by oheger-bosch** [comment]
@fviernau @mnonnenmacher @sschuberth: There is obviously no consensus how to deal with default values. How do we proceed with this ticket?

**Comment by sschuberth** [comment]
Over the weekend, I have started to experiment with Frank's proposal, but I forgot to push the branch from another machine. I'll refer to it from here for you guys to take a look.

**Comment by fviernau** [comment]
Thanks @sschuberth !

**Comment by sschuberth** [comment]
Here's finally the result of my experiments, see https://github.com/oss-review-toolkit/ort/pull/3731.

**Comment by oheger-bosch** [comment]
@sschuberth could you please elaborate how you are going to solve this ticket with the changes introduced by #3731? After applying this PR, the ORT configuration contains default values, but they are empty. Is there a step to come which moves the hard-coded default values from the code to these default configuration objects?

**Comment by sschuberth** [comment]
> Is there a step to come which moves the hard-coded default values from the code to these default configuration objects?

That was the idea, yes. I still need to experiment how feasible it is at the example of `ScanCode`'s `commandLineNonConfig`.

**Comment by sschuberth** [comment]
Closing this as we decided to go exactly the opposite way and use Kotlin code as the only source for default configuration.
