### ISSUE TITLE
ort scan requires python 3.6 issue 

### ISSUE THREAD

**Issue by rajatkumarco** [oss-review-toolkit/ort#3873]
on executing this command
![image](https://user-images.githubusercontent.com/58552459/114357470-63af6600-9b8f-11eb-920d-970cf7655936.png)
I am getting this error
![image](https://user-images.githubusercontent.com/58552459/114357361-48445b00-9b8f-11eb-9328-2adc2b8f33b8.png)
I also tried the mentioned solution, but that did not work
![image](https://user-images.githubusercontent.com/58552459/114357815-d28cbf00-9b8f-11eb-8d2e-4c64aedb81b6.png)
please help me here, I have python  3.9

**Comment by sschuberth** [comment]
As a side note, that message comes directly from Python (which gets executed by ORT), so also the suggested `-0` option needs to be passed to Python itself, not to ORT.

Anyway, the root cause here is that we ScanCode version we currently use still requires Python 3.6. The easiest work-around for you should be to locally configure ORT to use another ScanCode version, very similar to like done in https://github.com/oss-review-toolkit/ort/pull/3613.
