### ISSUE TITLE
Bug in webapp report - Scopes are wrongly categorized

### ISSUE THREAD

**Issue by Sheriff-Manzoor** [oss-review-toolkit/ort#3886]
Dear Team,

We notice that in maven webapp reports, the scopes are wrongly categorised for the packages listed.

compile scope as test and test scope as provided and provided scope as compile.

Sorry i am unable to attach screenshot for your reference due to some technical issues

**Comment by tsteenbe** [comment]
@Sheriff-Manzoor  Can you provide analyzer or scanner result so I can try to reproduce the issue?

**Comment by hanna-modica** [comment]
Added screenshot for @Sheriff-Manzoor:
![web-app-bug](https://user-images.githubusercontent.com/40762532/114840080-bcbd0b00-9dd6-11eb-8240-f7d8d99ee778.png)

**Comment by hanna-modica** [comment]
Today I had this problem again. If I filter for test scope, everything but test scope is shown.
![grafik](https://user-images.githubusercontent.com/40762532/141300467-5c461b67-fa6f-48f8-85b5-39070049db14.png)
@tsteenbe I cannot give you the results, since they contain company-specific information. If it helps, we could have a call regarding this issue.

**Comment by sschuberth** [comment]
> If I filter for test scope, everything but test scope is shown.

I just checked and cannot reproduce this: Filtering for "test" correctly only shows "test" scope dependencies only.

Please reopen if you can still reproduce this with a concrete example.
