### ISSUE TITLE
package config: Placeholders in referenced version?

### ISSUE THREAD

**Issue by patrickp-at-work** [oss-review-toolkit/ort#3997]
Hello,
I'm just getting started with ORT and I'm wondering about one part of the docs. Referring to [this section of the package exclude documentation](https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-package-configuration-yml.md#defining-path-excludes-and-license-finding-curations): I want to exclude a dependency from the evaluation _regardless of its version_ because I own it and it is covered by another OSS analysis already. 

The documentation tells:
> Each package configuration applies exactly to one package id and provenance which must be specified.

The ability to omit the version or use placeholders would be very helpful. If I understand the documentation correctly, one needs to update the package configuration whenever one bumps the version of any dependency that is mentioned therein. Isn't that causing needless maintenance toil?

Desired solution:
* possibility to declare an upwards-compatible version – as offered by the caret notation of npm: e.g. `^1.2.10` or completely omit the version
* If this is not currently offered due to implementation constraints, then the docs should say so.
* documentation refined in regards to this use-case

Pointer:
https://github.com/oss-review-toolkit/ort/commit/0aaff6b04c6121cf511d9438596f2b177d2fba2d by @fviernau

**Comment by fviernau** [comment]
@patrickp-at-work a package configuration is not meant to be used for excluding a dependency. 

For each package ORT scans either (1) a source artifact or (2) the VCS at a particular revision.
A package configuration sets up configuration for such scan in the context of one particular package.
You can correct false detections and setup excludes on file (lin nr) granularity.

> The ability to omit the version or use placeholders would be very helpful. 

There was some (lengthy to write) reason why this was intentionally not implemented.

> If I understand the documentation correctly, one needs to update the package configuration whenever one bumps the version of any dependency that is mentioned therein.

That's not correct. You may setup a new package configuration and optionally copy over some entries from the previous one.
I know redundancy is often times considered bad, however in this case I believe it makes a lot of sense.

> Isn't that causing needless maintenance toil?

I believe as-is, it minimizes maintainance toil, because of multiple reasons. For example, editing a package configuration becomes at least very expensive when it applies to multiple revisions just consider figuring out whether an entry is needed or double checking whether an entry is correct. The implementation as-is has a natural way for getting rid of technical debt / old unneeded things, because the entries for old library versions are not intermixed with the new one - and typically you only look at the newer versions of the file. 

I hope the above gives a direction of the underlying idea, I don't have the time to write this up in more detail right now.

**Comment by patrickp-at-work** [comment]
Thanks for answering, @fviernau. In fact, I got the direction of what you are saying but did not understand all parts of it. I will try to map it to our case in practice and see how it works out.

**Comment by sschuberth** [comment]
@patrickp-at-work, if your question has been answered (for now), please feel free to close this issue (and eventually reopen later in case of follow-up questions).
