### ISSUE TITLE
package.spdx.yml are discarded in MoveTK project

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#4251]
Previously for the MoveTK project (https://github.com/heremaps/movetk) the report would show SpdxDocumentFile entries and now the Analyzer logs shows the below:

```
10:11:59 08:11:59.287 [main] INFO  org.ossreviewtoolkit.analyzer.managers.SpdxDocumentFile - Discarded the following non-project SPDX files: '/workspace/project/src/include/third_party/miniball/package.spdx.yml', '/workspace/project/src/include/third_party/boost_geometry/package.spdx.yml', '/workspace/project/third_party/Catch2/package.spdx.yml', '/workspace/project/third_party/GsTL/package.spdx.yml'
```

This regression in functionality was introduced in https://github.com/oss-review-toolkit/ort/pull/3846 but per the https://github.com/spdx/spdx-spec/issues/439 this should work.

**Comment by tsteenbe** [comment]
MoveTK is just the public example - per spec for this it's not required to have project.spdx.yml for a project. Requiring to have one would break some of our and other ORT use cases.

**Comment by neubs-bsi** [comment]
From discussion with @tsteenbe on Friday:
Idea: 
- before starting `resolveDefintionFiles()` in the analyzer -> create a new function in PackageManager that runs before this and can implement definition file specific rules
- for `SpdxDocumentFile `this would be -> if `project.spdx.yml` exist, delete all` package.spd.yml`, otherwise keep them
- then in the `SpdxDocumentFile` `resolveDependencies`: delete discarding of the `package.spdx.yml` and return `package.spdx,yml` information if it is a definition file.

**Comment by neubs-bsi** [comment]
@tsteenbe do you by any chance still have an analyzer result file from an old MoveTK project that shows how you would expect the results to look?

**Comment by tsteenbe** [comment]
@neubs-bsi  Sure, here you go [movetk-november-30-2020-analyzer-result.json.zip](https://github.com/oss-review-toolkit/ort/files/6807099/movetk-november-30-2020-analyzer-result.json.zip)
