### ISSUE TITLE
Android library .aar packages are not considered as binary artifacts

### ISSUE THREAD

**Issue by heliocastro** [oss-review-toolkit/ort#4375]
Android libraries final generated package is suffixed as .aar. and not .jar,

Scanning projects with dependencies to this libraries will generate a warning, since the expected binary .jar is not present, i.e.;

> 10:56:49.809 [DefaultDispatcher-worker-3] WARN  org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Unable to find 'com.google.android.material:material::1.2.1' in any of [https://repo.maven.apache.org/maven2, https://artifactory.**.net/artifactory/external-maven-google-com/, https://artifactory.**.net/artifactory/external-jcenter-bintray-com/, https://artifactory.**.net/artifactory/external-gradle-org-plugins/, https://artifactory.**.net/artifactory/repo-maven-release, https://artifactory.**.net/artifactory/repo-maven, https://artifactory.cc.**.net/artifactory/repo-virtual]

Reference: https://developer.android.com/studio/projects/android-library#aar-contents

**Comment by sschuberth** [comment]
While indeed the [`material` library 1.2.1](https://mvnrepository.com/artifact/com.google.android.material/material/1.2.1) is packaged as an AAR, [ORT does support that packaging](https://github.com/oss-review-toolkit/ort/blob/2e216452db7db7c984306ff1d4d4f875ca1f2067/analyzer/src/main/resources/META-INF/plexus/components.xml#L13-L29).

The problem seems to be something else, as I can reproduce the issue in an Android project also for regular JARs, but *only* if I beforehand delete `~/.ort/cache/`.
