### ISSUE TITLE
What does `devDependencies` mean?

### ISSUE THREAD

**Issue by alex4200** [oss-review-toolkit/ort#4554]
In the [Getting Started Guide](https://github.com/oss-review-toolkit/ort/blob/master/docs/getting-started.md) in Section 5 (Run the scanner) a sentence reads:

`The mime-types package has only one dependency in the depenencies scope, but a lot of dependencies in the devDependencies scope.`

What does it mean? Does it mean, that with the `analyzer` only the direct dependencies are analyzed, but with the `scanner` all the lower level dependencies are analyzed? (I mean, when a package like `mime-type` depends on a package `moduleA`1, which depends on a `moduleB`, ...)?

Also, it is not clear what the `scanner` is doing in contrast to the `analyzer`, as here I already get a list of packages and their licenses...

**Comment by sschuberth** [comment]
> Does it mean, that with the `analyzer` only the direct dependencies are analyzed, but with the `scanner` all the lower level dependencies are analyzed?

No. The analyzer already gathers all transitive dependencies. But dependencies can be organized in scopes. And at the example of NPM, there can be a scope called [devDependencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#devdependencies).

The scanner then scans the source code of the dependencies that the analyzer gathered.

> Also, it is not clear what the `scanner` is doing in contrast to the `analyzer`,

This is described in the [analyzer](https://github.com/oss-review-toolkit/ort#analyzer) and [scanner](https://github.com/oss-review-toolkit/ort#scanner) sections of the `README.md`.

I guess what you're missing is the concept of *declared licenses* (as found by the analyzer; this is what the dependency *declares* itself to be licensed under) vs. *detected licenses* (as found by the scanner; this is what you can find actual *proof* for in the source code).

**Comment by sschuberth** [comment]
> What are " license / copyright scanners"?

No offense, but you seem to be lacking some very basic understanding / terminology used in the OSS compliance domain. Are you sure ORT is the right tool for you? As [here](https://github.com/oss-review-toolkit/ort/issues/4471#issuecomment-926483121) you agreed it's probably not.

Similarly, you seem to lack basic knowledge about how to operate tools like Docker, which makes it quite hard to give proper advice without starting with Adam and Eve. For general questions, please try to get answers on our [Slack workspace](https://join.slack.com/t/ort-talk/shared_invite/enQtMzk3MDU5Njk0Njc1LThiNmJmMjc5YWUxZTU4OGI5NmY3YTFlZWM5YTliZmY5ODc0MGMyOWIwYmRiZWFmNGMzOWY2NzVhYTI0NTJkNmY) instead of posting questions as issues.

> What I might understand, that the ORT _scanner_ combines other _scanners_. But it does not explain what a _scanner_ is!

In my opinion it does. It's a tool that "wraps" other scanners, calls them, and transforms the native scanner results into a common output format, so the results can be consolidated and compared.

> How can the license be detected from the code?

From license / copyright headers in the source code files, or from committed license files, etc. Of course, if there is no indication at all what the license could be, nothing can be detected. But that then simply means the scanner project does a bad job at its obligation to put its code under a license, as at least by German law any software that is not explicitly put under a license *must not be used at all*.

> Maybe you can suggest a book, article, tutorial, course where all this complicated stuff is explained for a beginner?

As you seem to be German-speaking, I'd recommend [this book](https://www.amazon.de/dp/3406734979/?coliid=IMOZJCL4NGD5K&colid=17LVFVEMOLX8V&psc=1&ref_=lv_ov_lig_dp_it).
