### ISSUE TITLE
How to provide custom license texts?

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#4740]
For a few licences there not exists a SPDX license text. So I tried to introduce a directory with custom license with the path following [this guide](https://github.com/oss-review-toolkit/ort/blob/master/docs/dir-custom-license-texts.md): ort/custom-license-texts. 

It contains the license text unrar.txt.

Example:
In curations.yml I have the following curation for the license:
```
- id: "Maven:com.github.junrar:junrar:7.4.0"
  curations:
    concluded_license: "unrar"
    declared_license_mapping:
      "UnRar License": "unrar"
```

It is declared in license-classifications.yml:
```
- id: "unrar"
  categories:
  - "proprietary"
  - "include-in-notice-file"`
```

I have run the report with:
`-O NoticeTemplate=template.path=/pxs-project/ort/customized_license_report.ftl,/pxs-project/ort/customized_license_text_summary.ftl` to generate a custom report.

I used the [code example in github](https://github.com/oss-review-toolkit/ort/blob/master/reporter/src/main/resources/templates/notice/default.ftl) for testing with customized_license_report.ftl:

The license is in the report but still without license text.

```
Package: com.github.junrar:junrar:7.4.0

The following copyrights and licenses were found in the source code of this package:
```

Have I done anything wrong in my case?

**Comment by sschuberth** [comment]
(Formatting hint: Please use triple backticks or an indentation of 4 spaces for code blocks.)

**Comment by mnonnenmacher** [comment]
@schvvarzekatze The problem is that ORT expects the license text file name to follow certain rules, but the file ending with ".txt" is not on that list. Supported patterns in your case would be:

* "unrar"
* "LicenseRef-unrar"
* "LicenseRef-[custom namespace]-unrar"
* "unrar.LICENSE"

See:

https://github.com/oss-review-toolkit/ort/blob/15a4cf9efda9755cd44f76d9cef8481783124702/utils/spdx/src/main/kotlin/Utils.kt#L166-L169

I would also recommend that you follow the [SPDX specification](https://spdx.github.io/spdx-spec/using-SPDX-short-identifiers-in-source-files/#e2-format-for-spdx-license-identifier) for your custom license names and prefix your custom license name with "LicenseRef-", ideally also with a custom namespace, for example "LicenseRef-schvvarzekatze-unrar" and then call your license text file accordingly "LicenseRef-schvvarzekatze-unrar" or ""LicenseRef-schvvarzekatze-unrar.LICENSE".

**Comment by schvvarzekatze** [comment]
Thank you very much for the explanation. Now it works.
