### ISSUE TITLE
Windows .Net project scan process performance issue / scancode spawned for packages w/o source VCS url

### ISSUE THREAD

**Issue by porsche-rbieniek** [oss-review-toolkit/ort#4828]
We have set up a test for processing a .Net analyzer-result.yml with about 450 unique NuGet packages referenced.
So far, we understand that most of the packages referenced are binary only w/o any reference to a source code repository attached to it.
After having processed roughly 300 package in the scan processing stage, we observed 

- 130 packages dont have a VCS URL attached
- 42 pacakges have a  VCS URL attached

Our expectations is that any package w/o a VCS url is **not** supposed to be prcessed by scancode because it does not have any scannable sources attached to it.
However, we learned that these pacakges are still being fed to scancode which leads to scancode delivering no results and just wasting CPU cycles

Our question here is if that is the intended behavior, and if so, what is the reasoning behind it?

Or is it just the case that this has been fixed in a more recent ORT version than that we are curenntly running in production (which is bsed on ORT in May 2021)´?

As a hint, we have checked the behavior in this particular test case with a current ORT version (from Github master)  and it seems to expose the same behavior

**Comment by mnonnenmacher** [comment]
The external scanner tools are not executed if ORT cannot download the source code, the relevant code is here:

https://github.com/oss-review-toolkit/ort/blob/15a4cf9efda9755cd44f76d9cef8481783124702/scanner/src/main/kotlin/PathScanner.kt#L258-L281

Please note that the wrapper class for ScanCode is also called `ScanCode` so you will see log lines starting with `org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode` even if the ScanCode binary is not called. If the external tool is executed you will see lines start with `org.ossreviewtoolkit.utils.common.ProcessCapture - Running '[...]/scancode --copyright --license --info --strip-root ...`.

For each package without VCS or source artifact information ORT will add a `ScanResult` with an error to the result, but performance wise this should not be relevant because the download functions exit early if this information is missing.

If you observe different behavior please let us know.

**Comment by sschuberth** [comment]
> If you observe different behavior please let us know.

Any update here, @porsche-rbieniek?

**Comment by sschuberth** [comment]
Meanwhile, the [DotNet / NuGet support has been completely rewritten](https://github.com/oss-review-toolkit/ort/pull/6209). Feel free to reopen if you're still having problems.
