### ISSUE TITLE
SW360 not working as storage for scan results 

### ISSUE THREAD

**Issue by porsche-rbieniek** [oss-review-toolkit/ort#5025]
IMHO the current SW360 implementation cannot be used as a storage backend for ORT scancode results.

After core review of the client usage on the side of ORT and the SW360 ReST server implementation, we concluded that the interaction between ORT and SW360 will not work as expected.
The reason is that the client used by ORT makes use of HTTP POST requrests for which no matching implementation in the SW360 codfe base can be found

This has been raised as a bug to the SW360 community [#1459](https://github.com/eclipse/sw360/issues/1459)

**Comment by sschuberth** [comment]
@bs-ondem can you maybe comment on that?

**Comment by bs-ondem** [comment]
@porsche-rbieniek ORT uses the interface `SW360ReleaseClientAdapterAsync` (which uses the extended class `SW360ReleaseClient` of `SW360AttachmentAwareClient<SW360Release>`) in order to upload attachments to the corresponding entity (in this case SW360Release). Therefore, the client makes HTTP POST requests to `/releases/{releaseId}/attachments` rather than to `/attachments`. The client shouldn't ever be able to make requests to `/attachments` because there isn't an extension class for `SW360AttachmentAwareClient<SW360Attachment>`.

**Comment by sschuberth** [comment]
@porsche-rbieniek can this be closed?

**Comment by sschuberth** [comment]
Closing this due to @bs-ondem's explanations. Feel free to reopen if the issue turns out to be valid.
