### ISSUE TITLE
Matching package configurations based on the source artifact url limits sharing

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#5361]
Some companies proxy repositories, for example NPM through Artifactory or other services. This leads to different `sourceArtifactUrl` for the packages:

json5 in NPM: https://registry.npmjs.org/json5/-/json5-1.0.1.tgz
json5 in Artifactory: http://145.132.127.126:8081/artifactory/api/npm/npm-project/json5/-/json5-1.0.1.tgz

This leads to package configurations made for the package from NPM not work for the package from Artifactory, leading to sharing of the package configuration not as effective. Would it make sense to match package configurations based on the source artifact hash instead?

**Comment by sschuberth** [comment]
> Would it make sense to match package configurations based on the source artifact hash instead?

That's maybe a question for @fviernau.

Other than that, extending and using [ClearlyDefined's "provider" concept](https://github.com/oss-review-toolkit/ort/issues/155) could be useful here, as we could configure [http://145.132.127.126:8081/artifactory/api/npm/npm-project/](http://145.132.127.126:8081/artifactory/api/npm/npm-project/json5/-/json5-1.0.1.tgz) to be the same provider (i.e. `NPM_JS`) as https://registry.npmjs.org/, and then allow matching based in providers instead of full URLs.

**Comment by sschuberth** [comment]
@mmurto are you fine with closing this as part of backlog grooming, or is there still a concrete need to keep this open, and a plan to implement it?

**Comment by mmurto** [comment]
I'm fine with closing.
