### ISSUE TITLE
Ability to merge multiple analyzer / scanner results into a single report

### ISSUE THREAD

**Issue by arieltorti** [oss-review-toolkit/ort#5620]
We are using ORT to extract licenses and export dependency graphs from our microservices.

Summarizing, our workflow is to periodically run ORT on each microservice before doing a release while having separate process generate aggregated reports of all our services. Currently we are generating individual reports for each repo, but we would like to have an aggregated report instead.

Would it be possible to merge several results from ORT Analyzer and ORT Scanner into one file so that we can export a single report for our entire codebase ?

**Comment by sschuberth** [comment]
I've changed the title to make more clear that the ask is not to merge a single analyzer result with a single scanner result (which, [as explained here](https://github.com/oss-review-toolkit/ort/issues/5617#issuecomment-1197729124), is not necessary as the scanner result includes the analyzer result).

Instead the request seems to be to merge multiple ORT result files (be it analyzer or scanner result files) into one in order to pass it to the reporter to create a single report.

As outlined in the similar issue https://github.com/oss-review-toolkit/ort/issues/4364 and the review of PR https://github.com/oss-review-toolkit/ort/pull/5317 which tried to implement merging of analyzer result files as a `helper-cli` command, this approach has various issues. One of them is that ORT result files can only record a single repository from which it was created, and when merging results, it would be unclear which one that should be.

That's why I've [proposed](https://github.com/oss-review-toolkit/ort/issues/4364#issuecomment-1197753117) to instead create a special reporter that can take multiple ORT result fields as input and creates a single combined attribution document as the output.

So, @arieltorti, would you be fine with closing this and continuing the discussion as part of https://github.com/oss-review-toolkit/ort/issues/4364?

**Comment by arieltorti** [comment]
Sounds good, it's the exact same use case and the solution you proposed works for us.

I'm fine with closing this issue.

**Comment by dgutson** [comment]
@arieltorti I think this should be a duplicate

**Comment by dgutson** [comment]
@sschuberth sorry if I'm not getting this, I'm confused: #4364 is Open but the PR is merged. What's the current status of the functionality? Does it still require some development? (we can help here)

**Comment by sschuberth** [comment]
@dgutson, the PR is not merged, but it was *closed* unmerged. Basically the same PR was recreated about 3 times due to the contributor having problems with Git, which makes things a bit hard to track. But long story short, there is no `helper-cli` command to merge analyzer results yet.

**Comment by dgutson** [comment]
So the only thing to get this working is https://github.com/oss-review-toolkit/ort/pull/5519 ? I want to know if there is more to be done, so we could help.

**Comment by sschuberth** [comment]
> So the only thing to get this working is #5519 ?

Yes, that's currently your best bet.

> I want to know if there is more to be done, so we could help.

That for offering help! Most of the ORT contributors are on summer vacation currently, so reviews will be slowed down a bit... but if you're interested in the feature, I'd say you could try out #5519 and review the code / leave feedback in the PR discussion.
