### ISSUE TITLE
Better understand how to install external tools: in docker?or in the code itself?

### ISSUE THREAD

**Issue by pombredanne** [oss-review-toolkit/ort#5631]
I am trying to understand how is a tool like scancode installed:
- I see https://github.com/oss-review-toolkit/ort/blob/918e64e8ebc8510ca5e5ed81d8e5620e0d2ce4c7/scanner/src/main/kotlin/scanners/scancode/ScanCode.kt#L170 which seems to fetch it live from a remote URL
- but this is also installed in the Dockerfile in https://github.com/oss-review-toolkit/ort/blob/918e64e8ebc8510ca5e5ed81d8e5620e0d2ce4c7/Dockerfile#L157

Is this possibly doing double duty? which one of these two will be used at runtime? Is there a context where the run is not done through Docker?

I see pipdeptree re-installed each time there is an analysis here: https://github.com/oss-review-toolkit/ort/blob/918e64e8ebc8510ca5e5ed81d8e5620e0d2ce4c7/analyzer/src/main/kotlin/managers/Pip.kt#L510

But poetry and pipenv are only installed globally in the Dockerfile https://github.com/oss-review-toolkit/ort/blob/918e64e8ebc8510ca5e5ed81d8e5620e0d2ce4c7/Dockerfile#L133  ?

Can poetry and pipenv be used also outside of a containerized run?
I am trying to find out what's the preferred way to get tools in... and how to best test them

**Comment by pombredanne** [comment]
We have a mostly working python-inspector integration working in https://github.com/nexB/ort/pull/1 and I would like to sort this out.

**Comment by oheger-bosch** [comment]
Since nobody from the experienced maintainers has answered so far, I can throw in my 2 cents; but you should wait for an "official" statement rather than taking this for granted.

The main README file lists multiple ways to run ORT commands, and using Docker is just one option. My understanding is that support for auto-installing tools is rather a legacy approach with the purpose of giving new users a good experience: Build ORT from its sources or download binaries, run it on your codebase, and everything you need will be downloaded and installed automatically. It turned out, however, that this approach is hard to maintain and might have problems with tools already installed locally in different versions. So there have already been discussions to remove this feature, but no final decision has been taken yet.

For the integration of new tools, I would therefore assume that the way to go is the inclusion of these tools in the Docker image and not providing some sort of auto-installation mechanism.

**Comment by oheger-bosch** [comment]
Hi @pombredanne,

we discussed the topic in our team in Bosch (including one of the core maintainers) and came to the conclusion that my answer is correct. So you can go ahead with your PR under the assumption that installing the tool in the Docker image is sufficient.

**Comment by pombredanne** [comment]
@oheger-bosch Thanks... this will simplify the build script that we edited to also install when build outside of Docker in https://github.com/nexB/ort/pull/1#issuecomment-1203075331
Now, would you know how to run the tests in the Docker context?

**Comment by MarcelBochtler** [comment]
> Now, would you know how to run the tests in the Docker context?

Re @pombredanne
The docker tests can be run by using [Batect](https://batect.dev/).
See https://github.com/oss-review-toolkit/ort/blob/4ad3fdfa82cd32df721919e73b3951e7b8770bf3/.github/workflows/build-and-test.yml#L119-L120

**Comment by pombredanne** [comment]
@MarcelBochtler Thanks!

**Comment by mnonnenmacher** [comment]
I would like to add one thing to what @oheger-bosch said: There only exception where we still prefer bootstrapping over adding a dependency to the Docker image is if the dependency is very large and would blow up the size of the Docker image, but is rarely used. This is currently the case with Flutter which would increase the size of the image by more than a gigabyte. For all other dependencies adding them to Docker should be preferred over bootstrapping.

I will close this as I think the question is answered.
