### ISSUE TITLE
downloader ssh auth failed / file cache behavior 

### ISSUE THREAD

**Issue by durr-hackenberg** [oss-review-toolkit/ort#5802]
Hello, 

sometimes GitHub calls will triggernd with SSH and Fail with "Auth failed". How can I solve the problem ? Do I need to create a .gitconfig ? 
![image](https://user-images.githubusercontent.com/99266785/190362440-220c8c4d-dbe4-4bd5-ae34-e0cb083d1317.png)

And I have another question regarding file cache. if I subsequently create a curlation.yml with an entry for a VSC and then run the scanner again does it then overwrite the binaries from maven org and extend the scan with the VSC export ? I have the feeling that this will not happend - Im not sure if it working like that. Actually, I just want to reduce the runtime of the scanner so that it doesn't take so long. 

Thank you!

**Comment by sschuberth** [comment]
> sometimes GitHub calls will triggernd with SSH and Fail with "Auth failed". How can I solve the problem ?

The easiest way probably is to run an SSH agent on the machine running ORT.

> And I have another question regarding file cache.

Please don't ask multiple unrelated questions in the same issue; that makes it hard for us to decide when to close the issue.

> if I subsequently create a curlation.yml with an entry for a VSC and then run the scanner again does it then overwrite the binaries from maven org and extend the scan with the VSC export ?

No binaries are being overwritten because none are stored by ORT. However, package metadata is over*ridden* by package curations. By [default](https://github.com/oss-review-toolkit/ort/blob/63e002ba57e7d49c96017fac2ff679de8a5b76df/model/src/main/kotlin/config/DownloaderConfiguration.kt#L38-L41), ORT's downloader prefers to download from VCS (not VSC 😉) instead of source artifacts if both are specified. So curating VCS information will make the downloader clone the source code location specified in the curation instead of the original VCS location mentioned in the package metadata (if any).

In that sense the scan result will also not be "extended", but the old scan results for that package will be replaced with new ones from the curated VCS location.

**Comment by durr-hackenberg** [comment]
Ok, sorry :) 
Thank you for the answer. I think with that it is clear for me!
