### ISSUE TITLE
Downloader: Sparse checkout not working

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6043]
The `vcs-path` parameter does not take any effect. Reproduce with the following command:

```
$HOME/sources/ort/cli/build/install/ort/bin/ort \
      --info download \
      --project-url https://github.com/spdx/spdx-examples.git \
      --project-name project \
      --vcs-type git \
      --vcs-revision "b942fb106bbe6537481e70d26d872ab91ff87323" \
      --vcs-path "example4" \
      --output-dir .
```

**Comment by sschuberth** [comment]
@fviernau I believe this is due to all example directories containing `README.md` files (see e.g. [here](https://github.com/spdx/spdx-examples/tree/b942fb106bbe6537481e70d26d872ab91ff87323/example1)), and our default sparse-checkout patters are

```
*.ort.yml
**/copying*
**/COPYING*
**/Copying*
**/copyright
**/COPYRIGHT
**/Copyright
**/licence*
**/LICENCE*
**/Licence*
**/license*
**/LICENSE*
**/License*
**/*.licence
**/*.LICENCE
**/*.licence
**/*.license
**/*.LICENSE
**/*.license
**/unlicence
**/UNLICENCE
**/Unlicence
**/unlicense
**/UNLICENSE
**/Unlicense
**/patents
**/PATENTS
**/Patents
**/readme*
**/README*
**/Readme*
```

so these directories are always included. I've verified that manually removing these and only keeping `/example4` as a sparse-checkout pattern only checks out the `example4` directory.

**Comment by sschuberth** [comment]
Feel free to reopen if required.
