### ISSUE TITLE
Gradle Analyzer: Use Declared Repositories to Download Artifacts

### ISSUE THREAD

**Issue by maklostermann** [oss-review-toolkit/ort#6488]
We use an internal Maven repository, but during Gradle analysis it tries to download from the "original" repository (found in POM). If this fails, it will also try the declared repositories. In our case, network restrictions will cause connection timeouts and the analysis takes very long.

Related code in MavenSupport.kt:
`val allRepositories = (artifactDescriptorResult.repositories + repositories).toSet()`

In my case, completely omitting the artifactDescriptorResults, the only changes in the analyzer output are binary_artifact.url and source_artifact.url.

This would not only solve my issue regarding the network restrictions, but also provide the **correct** information as the build will also use these sources.

Wouldn't it be better to only add the repositories from POM (artifactDescriptorResults) only if there is no declared repository? Or at least to change the order, to use the declared repositories first?

**Comment by sschuberth** [comment]
> Wouldn't it be better to only add the repositories from POM (artifactDescriptorResults) only if there is no declared repository? Or at least to change the order, to use the declared repositories first?

These are interesting questions. So far I was pretty certain that Maven would first look at repos defined in a POM, and then at globally (e.g. via `settings.xml`) defined repos, as it feels more natural that each artifact knows best for itself where go gets its dependencies form. However, that order would not allow to override all repos e.g. with a company-internal mirror / proxy. That probably why [Maven defines this order](https://maven.apache.org/guides/mini/guide-multiple-repositories.html#repository-order):

> Remote repository URLs are queried in the following order for artifacts until one returns a valid result:
>
> * Effective settings:
>   * Global settings.xml
>   * User settings.xml
> * Local effective build POM:
>   * Local pom.xml
>   * Parent POMs, recursively
>   * Super POM
> * Effective POMs from dependency path to the artifact

So from that perspective it indeed seems like we should swap the order here (and probably use `distinct()` instead of `toSet()` to more clearly indicate that the order matters).

Let's see [what Gradle has to say](https://docs.gradle.org/current/userguide/declaring_repositories.html#strict_limitation_to_declared_repositories) esp. about repos declare in POMs of dependencies:

> Maven POM metadata can reference additional repositories. These will be *ignored* by Gradle, which will only use the repositories declared in the build itself.

Ouch. As the `MavenSupport` class is also used by our Gradle analysis, it looks like we always did the wrong thing here by taking repos from POMs into account.

I'd be very curious about the opinion of @mnonnenmacher here.

**Comment by sschuberth** [comment]
@maklostermann, I've hacked together a draft at https://github.com/oss-review-toolkit/ort/pull/6489. Would you be so kind to give it a try and see whether that would address your issue?

**Comment by maklostermann** [comment]
@sschuberth, this works well in our case. 

There might still be an issue. Although the scan works and the result file contains our repository in the urls, log says that it still uses repo.maven.apache.org (last message below):
```
10:32:15.673 [DefaultDispatcher-worker-2] DEBUG org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Found 'org.jacoco:org.jacoco.agent:jar:0.8.7' in 'https://internal-repo/repository/maven/ (https://internal-repo/repository/maven/, default, releases+snapshots)'.
10:32:15.674 [DefaultDispatcher-worker-2] DEBUG org.eclipse.aether.internal.impl.DefaultTransporterProvider - Using transporter HttpTransporter with priority 5.0 for https://internal-repo/repository/maven/
[...]
10:32:15.678 [DefaultDispatcher-worker-2] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /repository/maven/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7.jar.sha1 HTTP/1.1
[...]
10:32:15.913 [DefaultDispatcher-worker-2] DEBUG org.ossreviewtoolkit.utils.ort.OkHttpClientHelper - Downloaded from https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7.jar.sha1 via network.
```

Not sure if this is just a logging issue or has side effects.

**Comment by sschuberth** [comment]
> Downloaded from https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7.jar.sha1

I believe that's due to our logic that tries to set [a package's `isModified` flag](https://github.com/oss-review-toolkit/ort/blob/f6c938659a224bd65eb36f38fd4e8cb917fc7cab/model/src/main/kotlin/Package.kt#L129-L134) correctly by comparing the hash of an artifact not coming from Maven Central with its hash on Maven Central (if the artifact is also present there), see this code:

https://github.com/oss-review-toolkit/ort/blob/f6c938659a224bd65eb36f38fd4e8cb917fc7cab/analyzer/src/main/kotlin/managers/utils/MavenSupport.kt#L305-L321

So still seeing the `repo.maven.apache.org` host in the log should be ok in this case.

**Comment by sschuberth** [comment]
> Thanks for the fast response!

Thanks for the report an investigation beforehand! This makes it far easier to respond fast 😉
