### ISSUE TITLE
OSV advisor TODO in C++

### ISSUE THREAD

**Issue by dgutson** [oss-review-toolkit/ort#6536]
I found this TODO in the OSV advisor: https://github.com/oss-review-toolkit/ort/blob/af0a83a2f83b2fe80ee7e0559f135200a65478fc/advisor/src/main/kotlin/advisors/Osv.kt#L165

Also, I noticed that Conan is not there.

Could someone please detail what is missing/needed, so we can determine whether we need to contribute to this? We are C++ users and would like to ensure we are not missing any advisory.

Thanks.

**Comment by sschuberth** [comment]
> Also, I noticed that Conan is not there.

Probably OSV added Conan support after we did 😉 I've added the mapping in https://github.com/oss-review-toolkit/ort/pull/6537.

> Could someone please detail what is missing/needed, so we can determine whether we need to contribute to this? We are C++ users and would like to ensure we are not missing any advisory.

In general, probably @fviernau knows best about the capabilities of OSV and how it deals with C++ projects.

Independently of that, here are my 2 cents: What matters is not so much the programming language, but the package / dependency manager. So when you say "C++", do you mean

- "Loose" C++ source code, probably in something like a mono-repo, where everything is built from source, including libraries / dependencies
- A Conan-managed C++ project with well-declared dependencies
- Something CMake-based
- Something else

Because for everything but the Conan-case it's going to be pretty hard to look up vulnerabilities, simply because it's unclear what the key for the lookup should be if you don't have a well-defined name for the package / dependency as implied by the use of a package / dependency manager.

For example, say you don't use Conan but have a directory called `lib/openssl` in your source tree, then maybe *you* know that this directory contains the source code to OpenSSL version 1.1.1 (for example), but ORT does not know, and even if it would, it would be unclear how to generate a unique name from it for vulnerability lookup (it could be "OpenSSL-v1.1.1", "openssl@1.1.1" etc.).

**Comment by dgutson** [comment]
@sschuberth I can't provide many details but let's say there's a neat Conan manifest file.

**Comment by sschuberth** [comment]
Ok, then I'd expected it to "just work" with #6537 merged and the OSV advisor enabled.

**Comment by dgutson** [comment]
So the TODO in the code is obsolete? There's nothing left TO-DO?

**Comment by sschuberth** [comment]
> So the TODO in the code is obsolete? There's nothing left TO-DO?

I'm unsure. It depends on whether "C++ projects" referred exclusively to "Conan projects", and how "requesting vulnerabilities by commit-ish" is supposed to work. Again @fviernau might be able to tell.

**Comment by dgutson** [comment]
@sschuberth @fviernau thanks for the wording clarification, now:
```
 TODO: Support querying vulnerabilities by Git commit hash as described at https://osv.dev/docs/#section/OSV-API.
    //       That would allow to generally support e.g. C / C++ projects that do not use a dedicated package manager
    //       like Conan.
```
Could you please file an issue addressing this TODO, with as much information as possible? From the comment, I can tell it is a useful case for us for *some* cases where a conan manifest may not be available (we have many projects).

**Comment by sschuberth** [comment]
> Could you please file an issue addressing this TODO, with as much information as possible?

@dgutson, I'd actually appreciate if *you* could file that issue, esp. as we probably don't have any more information than you do / what's written in the TODO already. I value issues reports created directly by our users as it more clearly shows where their priorities are. You could start off easily by clicking on "..." in the upper right of your own post and select "Reference in new issue".

**Comment by dgutson** [comment]
Ok, I thought you did have more information than that of the comment.
