### ISSUE TITLE
Reporter: spdx files missing data

### ISSUE THREAD

**Issue by qequ** [oss-review-toolkit/ort#6749]
Working on a repo I noted that a dependency listed in spdx has no license (concluded, declared) nor homepage

![Screenshot from 2023-03-27 17-45-02](https://user-images.githubusercontent.com/19431622/228062450-ae7eefda-5609-4d19-a3f8-fd21695dc5cc.png)

Checking the same dependency in the Web-App lists the data correctly

![Screenshot from 2023-03-27 17-40-21](https://user-images.githubusercontent.com/19431622/228062787-92ba82b6-c1c9-40c6-b52a-82503655f943.png)

CC: @dgutson

**Comment by dgutson** [comment]
@sschuberth @fviernau spdx.homepage shouldn't be equivalent to web-app.ProcessedRepository?

**Comment by sschuberth** [comment]
> spdx.homepage shouldn't be equivalent to web-app.ProcessedRepository?

No, it shouldn't. Please [see the SPDX specs](https://spdx.github.io/spdx-spec/v2.3/package-information/#711-package-home-page-field). A homepage URL is a homepage URL, and a repository URL is a repository URL. However, in lack of a dedicated homepage, some projects declare their repository URL as the homepage URL in their package metadata. But that's no interpretation / mapping that ORT does. We take the metadata as-is here.

**Comment by dgutson** [comment]
Then what about VCS location or some other VCS related field? Look, @qequ and I stayed until very late in the night manually fixing dozens of entries that looked like inconsistencies, I may understand that some metadata may be different or have some inconsistency, but I think that ORT could do some more coverage of grouping some more cases. In most of the casesbthe information was in the analysis results yaml and the webapp, and was not in the spdx, so I just copy pasted it.

**Comment by dgutson** [comment]
Because of the enormous effort we took and still internally sponsor ORT, would you mind to analyze this project and see what could had happened?

**Comment by sschuberth** [comment]
> Then what about VCS location or some other VCS related field?

What exactly do you mean? Where URL to a VCS location is in SPDX output? It's basically like this: ORT has more metadata about a package than we can squeeze into a single SPDX package. That's why a single ORT package is usually split into three (!) SPDX packages: The binary package, the belonging VCS package ("-vcs" suffix in the id), and the belonging sources artifact package ("-source-artifact" in the id). The `downloadLocation` of the binary package points to the binary artifact, the `downloadLocation` of the belonging VCS package point to the VCS repository, and the `downloadLocation` of the source package points to the source artifact.

> In most of the casesbthe information was in the analysis results yaml and the webapp, and was not in the spdx, so I just copy pasted it.

While I still believe that is most cases this is due to misunderstandings of the SPDX spec (which is horrible, BTW), I don't understand why don't instead adjust the SPDX reporter to your needs, and eventually contribute your changes back. That should scale much better.

**Comment by sschuberth** [comment]
> Because of the enormous effort we took and still internally sponsor ORT, would you mind to analyze this project and see what could had happened?

While I appreciate your use of ORT, I hope you realize that over the past weeks we as a maintainer team were quickly jumping at almost ever issue you filed, and helped you guys where we could without knowing anything about you or your use-case, or getting anything back.

So if you now ask us to do your day-job work, maybe you should consider sponsoring ORT not internally, but externally 😉

**Comment by sschuberth** [comment]
> a dependency listed in spdx has no license (concluded, declared) nor homepage

As the homepage bit has been [clarified](https://github.com/oss-review-toolkit/ort/issues/6749#issuecomment-1486501767) and [the declared license is not cleared anymore](https://github.com/oss-review-toolkit/ort/pull/6760) I believe we're good to close this.
