### ISSUE TITLE
Yarn :: Analyzer is reading Packages package.json scopes wrongly 

### ISSUE THREAD

**Issue by porsche-rishisaxena** [oss-review-toolkit/ort#6978]
We have a root level package.json and package directory have their respective package.json. When analyzer is executed on the root level, the scopes (devdependencies Vs dependencies) are written wrongly in the analyzer-result. A correctly defined dev-dependency package in package.json is marked in analyzer-result.yml under dependency. 

![image](https://user-images.githubusercontent.com/87651181/236876990-50c0f766-c85b-4af3-91d2-480d5a22f655.png)

**Comment by sschuberth** [comment]
Could be the related to https://github.com/oss-review-toolkit/ort/issues/6239.

**Comment by porsche-rishisaxena** [comment]
@sschuberth 
[analyzer-result.txt](https://github.com/oss-review-toolkit/ort/files/11450094/analyzer-result.txt)
Note: After download, change the file extension to .yml

**Comment by porsche-rishisaxena** [comment]
@sschuberth: Any update on this issue?

**Comment by sschuberth** [comment]
No, no one is actively working on it AFAICT.

**Comment by sschuberth** [comment]
@porsche-rishisaxena, before anyone can look into this, I believe we first need to

1. verify that the issue is still reproducible with the latest version of ORT,
2. show that the issue is different from #6239 (i.e. show that it is not only a display issue in the web-app report, but that the scope is already wrong in the original ORT analyzer result),
3. provide steps to reproduce with public sources (i.e. a public Git repository to analyze where the issue appears).

**Comment by sschuberth** [comment]
To clean up stale issues, I'm closing this as an assumed duplicate of #6239. Feel free to reopen if you can prove it is not a duplicate, but a separate issue.
