### ISSUE TITLE
Add support for Hex packages

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#728]
Add support for Hex packages (projects written in Elixir and Erlang) to the ORT analyzer module.

[About Hex](https://hex.pm/about):

 > Hex is a package manager for the BEAM ecosystem, any language that compiles to run on the BEAM VM, such as Elixir and Erlang, can be used to build Hex packages.... Many build tools support Hex packages including **Mix** for _Elixir_ projects, **rebar** and **erlang.mk** for _Erlang_ projects.

However, the use of the build tools is not as clear-cut as this, see also [Requirements 1](#Requirements) below. In general, a Hex package can use the following build tools:

- Mix
- rebar3
- rebar3 with erlang.mk
- both Mix and rebar3

## Requirements

1. Detect whether a project is a Hex project and whether it uses Mix or rebar

> - Mix:
>   - The presence of [mix.exs](https://hexdocs.pm/mix/Mix.html) and/or mix.lock may indicate that the projext build tool is Mix
> - rebar: 
>   - The presence of [rebar.config](https://www.rebar3.org/docs/dependencies), [rebar.lock](https://www.rebar3.org/docs/dependencies#section-lock-files), and/or [src/<myapp>.app.src file](https://hex.pm/docs/rebar3_publish#adding-metadata-to-code-classinlinesrcltmyappgtappsrccode) makes it likely the project build tool is rebar3. 
> - We could use the above files for the [globsForDefinitionFiles](https://github.com/heremaps/oss-review-toolkit/blob/master/analyzer/src/main/kotlin/managers/CocoaPods.kt#L40)

> However, the use of the build tools is not as clean-cut as this. For example, the project [ssl_verify_fun](https://hex.pm/packages/ssl_verify_fun) makes use of both Mix and rebar3. 

2. Detect declared license for a package

> - Mix:
>   - Licenses can be declared in the mix.exs see https://github.com/semlabs/kudos/blob/c36f23760992793962fd90aabf0630ccbd6e7530/mix.exs#L41
>     - Is this a standard? Mix docs do not provide an answer.
> - rebar3:
>    - Licenses can be declared in [src/<myapp>.app.src file](https://hex.pm/docs/rebar3_publish#adding-metadata-to-code-clas (and Mix/rebar3) sinlinesrcltmyappgtappsrccode)

3. Get dependency tree including package names, versions

> Options:
> - rebar3:
>   - use `rebar3 deps` or `rebar3 pkgs`, but note there is no machine-readable  output:
>    ```
>    → rebar3 deps
>    ...
>    cowboy* (package)
>    recon* (git source)
>    erlware_commons (locked git source)
>    getopt* (locked git source)
>    providers (locked hg source)
>    relx (locked git source)Erlang have scopes
>    ```
>    ```
>    → rebar3 tree
>    ...
>    |- bootstrap-0.0.2 (git repo)
>    |- dirmon-0.1.0 (project app)any 
>    |- file_monitor-0.1 (git repo)
>    |- peeranha-0.1.0 (git repo)
>    |  |- gproc-git (git repo)
>    |  |- interclock-0.1.2 (git repo)
>    |  |  |- bitcask-1.7.0 (git repo)
>    |  |  |  |- lager-2.1.1 (hex package)
>    |  |  |  |  |- goldrush-0.1.6 (hex package)
>    |  |  |- itc-1.0.0 (git repo)
>    |  |- merklet-1.0.0 (git repo)
>    |- recon-2.2.2 (git repo) on which to test Mix/rebar3 support
>    |- uuid-1.5.0 (git repo)
>    |  |- quickrand-1.5.0 (git repo)
>    ```
>   Documentation:
>
>   - https://www.rebar3.org/docs/commands#section-deps
>   - https://www.rebar3.org/docs/commands#section-pkgs
>   - https://www.rebar3.org/docs/dependencies#section-dependency-lock-management

> - Mix:
>   - install and use [licensir](https://github.com/unnawut/licensir) -- lists all licenses (Mix projects only)
>   - (or) write a script (in Erlang?) to loop over definition files and use Mix.Dep API (see https://github.com/semlabs/kudos/blob/master/lib/kudos.ex#L83-L100), but generate JSON
> - https://repo.hex.pm???

4. Obtain the source for a dependency

> - How can ORT's downloader download sources for an Erlang package?
> - Further investigation for Mix required: https://hexdocs.pm/mix/Mix.SCM.html.

5. Determine how to separate code dependencies from build/test ones

> - Are scopes supported/recognised in Mix/rebar3? 
> - rebar3 has the concept of [profiles](https://www.rebar3.org/docs/profiles) (default, native, prod, test) which we possibly could use to do this.

6. Implementation is not to use exeternal plugins to analyze Hex (Mix/rebar3) projects

Example Hex projects:

> - Mix: 
>   - https://github.com/jshmrtn/iona -- mix.exs names dependencies and package license
>   - https://github.com/unnawut/licensir -- mix.exs names dependencies
> - rebar3: 
>   - https://github.com/certifi/erlang-certifi -- no dependencies in rebar.config, licenses in src/certifi.app.src
>   - https://github.com/benoitc/erlang-idna
> - rebar3 and erlang.mk:
>   - https://hex.pm/packages/mimerl -- rebar.config does not list dependencies, they are fetched by erlang.mk
> - Both Mix and rebar3:
>   - https://hex.pm/packages/ssl_verify_fun -- neither mix.exs nor rebar.config list any dependencies

**Comment by fviernau** [comment]
@adambhere looking at above comments in the description I thought I'd share my two cents on `requirement 1`: Actually I can't see an issue with projects using both, mix and rebar, like the mentioned `ssl_verify_fun` project does. We could have two completely independent package manager implementation for mix and rebar would result in (1) a mix and (2) a rebar project being detected. It's up to the user then to `exclude the not relevant one(s)` via `path excludes`.

**Comment by tsteenbe** [comment]
To analyze Hex packages we may be able to use https://github.com/voltone/sbom. May Bram Verburg (@voltone) is willing to help us - let me try to reach out to him.

**Comment by voltone** [comment]
Let's first talk about Mix and Rebar3, putting Erlang.mk aside for now...

You probably won't encounter multiple build files in top-level projects: they are typically used to allow a package to be used as a dependency in both Erlang projects and Elixir projects. It is up to the build tool used at the project top-level to pick the correct file for the dependency subtree it is building (or, before that, for dependency resolution).

The lock files do not contain sufficient information, so I think one way or another you're going to have to call out to the build tool. Which tool should be used can be determined based on the presence of the lock file.

There is good news and bad news about both Rebar3 and Mix:

Rebar3, unlike Mix, defines a public API for fetching dependency information [rebar_state:all_deps/1](https://www.rebar3.org/docs/plugins#section-rebar-state-manipulation). Unfortunately I don't think it is possible to call it from a script, the way e.g. `bundler_dependencies.rb` does for Ruby. It is part of the plugin API, so it seems the user would have to add a plugin, such as [rebar3_sbom](https://github.com/voltone/rebar3_sbom), to the project in order to make the data available to Analyzer. Not sure if that's acceptable/practical.

As for Mix, it should be possible to introspect a project from a one-off script. Unfortunately there is no public API like there is in Rebar3, so the script would have to rely on undocumented internals of Mix/Hex. I've been meaning to define the minimum functionality needed, so I can propose an API to the Mix/Hex teams, but that doesn't help you right now.

In both cases, fetching the packages is best left to the build tools themselves, the introspection functions should provide information about the declared license, or you can look up the path where the package is installed and look for license files there.

Hope this helps. I haven't used oss-review-toolkit myself, and I'm not familiar with the constraints you have for interacting with build tools and package repos. Let me know what you think based on the above and I'll be happy to see if I can help move things forward.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.

**Comment by sschuberth** [comment]
For follow-ups please see https://github.com/stritzinger/sosef/issues/74 and https://github.com/stritzinger/sosef/issues/75.
