### ISSUE TITLE
Gradle analyzer not working Gradle 8.2+

### ISSUE THREAD

**Issue by AnishaM7** [oss-review-toolkit/ort#7369]
Gradle scans are not working with latest ort docker image, 
Ort image uses gradle is 8.2 and gradle packages are not fetched by analyzer module
![image](https://github.com/oss-review-toolkit/ort/assets/62882541/363ae571-d040-4600-af5d-cdff0eac31a8)

Same project, when scanned with older image of ort using gradle version 8.0.1, analyzer executes successfully and shows 7 packages in result
![image](https://github.com/oss-review-toolkit/ort/assets/62882541/f5bb14f1-336d-4fd6-b770-d1573f49e299)

What is the reason for this/ how to resolve the same

**Comment by tsteenbe** [comment]
Thank you @AnishaM7  for reporting your issue. Could you provide reproduce your issue with a publicly available repository?

**Comment by MarcelBochtler** [comment]
@tsteenbe, even this very simple test project using Gradle 8.2: https://github.com/MarcelBochtler/gradle82test
When running the analyzer on this project, no depenencies are being detected (tested with latest ort main).
Using Gradle 8.1 fixes this issue.

This only happens when using the default / legacy Gradle analyzer. Switching to the `GradleInspector` fixes the issue with the project above.

@AnishaM7 please try to use the `GradleInspector` by activating it in your `config.yml`:
```yaml
analyzer:
    enabledPackageManagers:
    - GradleInspector
```

**Comment by sschuberth** [comment]
Any update @AnishaM7?

**Comment by sschuberth** [comment]
Closing due to a lack of feedback from the OP. In any case, recently several Gradle issues were fixed (also see https://github.com/oss-review-toolkit/ort/issues/8027), so there is a good chance that this issue got fixed as well.
