### ISSUE TITLE
Double-check the `GitHubIssue.closedAfter()` implementation

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#7810]
@oheger-bosch, the first `!closed` condition looks wrong here:

https://github.com/oss-review-toolkit/ort/blob/df0ba6ef63ff770aea52720babfbb64cfc6af802/plugins/advisors/github/src/main/kotlin/GitHubDefects.kt#L346-L351

Mind elaborating whether this is as intended, esp. how closed issues without a close date should be handled?

**Comment by sschuberth** [comment]
To clarify, I would have more expected something like

    (closed && closedAt == null) || (closedAt != null && Instant.parse(closedAt).isAfter(time))

or even just

    closedAt != null && Instant.parse(closedAt).isAfter(time)

However, both make a ton of tests fail 😕

**Comment by sschuberth** [comment]
Also see the probably related https://github.com/oss-review-toolkit/ort/security/code-scanning/3152 hint.

**Comment by oheger-bosch** [comment]
Hm, it has been a while...

The context of this function is to find a release in which the issue has been fixed. This is not straight-forward, because there is no direct connection between issues and releases, but the association can only be done via release dates. IIRC, my original line of thoughts was that if the `closed` flag is *false*, the issue can be considered to be closed after any date (assuming a date not in the future). So, no release would be matched.

I guess, the question boils down to the exact relation between the `closed` and `closedAt` properties. Is it possible that they are not in sync? The current implementation gives priority to the `closed` flag and assumes that if it is *false*, the issue is still open and can thus not be fixed in any release. Maybe it is necessary to have a look at concrete GitHub issues to see how these properties behave in practice?

**Comment by sschuberth** [comment]
> he current implementation gives priority to the `closed` flag and assumes that if it is _false_, the issue is still open and can thus not be fixed in any release.

Actually, AFAIU the current implementation does the opposite: If `closed` is `false`, then `!closed` is `true`, which means no further `||` condition is checked, and `closedAt()` returns `true` independently of the `time`. So if the issue is not `closed`, it is always `closedAt`, which IMO makes no sense either way. Or am I missing something @oheger-bosch?

**Comment by oheger-bosch** [comment]
The logic is indeed tricky, I am afraid.

The code tries to find a release for the passed in package to obtain a release date. Then it tries to find all issues that affect this release. These are the issues still open or the ones that have been closed after the release date. This is what the `closedAfter()` function checks. So, a result of *true* means that the issue is present for this release. Therefore, the open issues (`!closed` is `true`) should be contained in this set.

**Comment by sschuberth** [comment]
Obsolete as of https://github.com/oss-review-toolkit/ort/pull/8994.
