### ISSUE TITLE
Cannot find ScanCode license texts in Docker image

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#8147]
ORT cannot find the ScanCode license texts in the Docker image:

```bash
$ docker run --rm ghcr.io/oss-review-toolkit/ort:13.0.0 requirements
[...]
ScanCode license texts not found.
```

The locations of the ScanCode binary and the license texts within the image are:
`/opt/python/shims/scancode`
`/opt/python/versions/3.11.5/lib/python3.11/site-packages/licensedcode/data/licenses`

The heuristic to find the license texts based on the path of the ScanCode binary fails for this:
https://github.com/oss-review-toolkit/ort/blob/f88041afc23b1950583efac0b396f41504e1c8ee/utils/spdx/src/main/kotlin/Utils.kt#L47-L54

**Comment by sschuberth** [comment]
My proposal is to actually *not* fix this by adjusting the heuristic to find the license texts, at least not as a long-term solution. Instead, we should probably make use of the [new `scancode-license-data` command](https://github.com/nexB/scancode-toolkit/issues/2738#issuecomment-1890455719). And I'd wish that before even doing that, we'd have the time to also extract license text providers to a proper interface / plugins.

**Comment by sschuberth** [comment]
> extract license text providers to a proper interface / plugins.

I've created https://github.com/oss-review-toolkit/ort/issues/9620 for this now.

**Comment by sschuberth** [comment]
Thinking about this again, can it be that the issue was a red herring? While it's correct that `scanCodeLicenseTextDir` (which is what `ort requirements` calls) returned `null` before #9622, that should not actually have mattered for the use-case of disclosure document generation, as

https://github.com/oss-review-toolkit/ort/blob/958c08cd8c4847ff55b05c59a64b4f9a987f124e/utils/spdx/src/main/kotlin/Utils.kt#L120-L138

actually first tries to read license texts from ORT's built-in [resources](https://github.com/oss-review-toolkit/ort/tree/main/utils/spdx/src/main/resources) before falling back to `scanCodeLicenseTextDir`.

So @wkl3nk can you confirm that there actually was an issue with any disclosure documents? If so, for which license ID?

**Comment by mnonnenmacher** [comment]
> So [@wkl3nk](https://github.com/wkl3nk) can you confirm that there actually was an issue with any disclosure documents? If so, for which license ID?

To my knowledge the issue was not related to SPDX licenses but only licenses starting with "LicenseRef-scancode-".

**Comment by sschuberth** [comment]
> To my knowledge the issue was not related to SPDX licenses but only licenses starting with "LicenseRef-scancode-".

I see. There are indeed not part of https://github.com/oss-review-toolkit/ort/tree/main/utils/spdx/src/main/resources/licenserefs. Something to reconsider, maybe.
