### ISSUE TITLE
Upgrade `Go` to next major version

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#8443]
Simply upgrading `Go` makes `GeDepFunTest` fail, which contains a bit of technical debt which needs to be removed in scope of this ticket.

**Comment by sschuberth** [comment]
FYI, "[As of 2020, Dep is deprecated and archived in favor of Go modules](https://github.com/golang/dep)", so we could probably drop `dep` support instead of fixing the underlying issue. 

@haikoschol, as the Go guy, to you have any feeling for how valuable it would be for ORT to maintain `dep` support still?

**Comment by haikoschol** [comment]
> FYI, "[As of 2020, Dep is deprecated and archived in favor of Go modules](https://github.com/golang/dep)", so we could probably drop `dep` support instead of fixing the underlying issue.
> 
> @haikoschol, as the Go guy, to you have any feeling for how valuable it would be for ORT to maintain `dep` support still?

I think it can be removed.

I don't remember the last time I saw an active project using it. I just did a quick [search on GitHub](https://github.com/search?q=Gopkg.toml+language%3ATOML&type=code&l=TOML) and the first few projects either haven't been updated in over two years or switched to Go mod and kept the old `dep` definition files in the repo.

**Comment by fviernau** [comment]
@sschuberth @mnonnenmacher I would go ahead and "implement" the removal now, ok ?
