### ISSUE TITLE
Bazel: Change the identification of registry URLs

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#8796]
The current implementation of Bazel in ORT use the `flags` property to identify the registry URLs:
https://github.com/oss-review-toolkit/ort/blob/main/plugins/package-managers/bazel/src/main/kotlin/BazelModel.kt#L37

This property has been removed with Bazel 7.2 so another way of identifying the registry URLs must be implemented.

These is a comment from a Bazel developer on their Slack channel (https://bazelbuild.slack.com/archives/CA31HN1T3/p1718960097739549):

> The registry flags are no longer recorded in the lock file. 7.2 has a new format that gets rid of a lot of duplicated information.
> The docs on the lockfile content are informational only, the exact format is explicitly not specified (it's viewed as an implementation detail)

and two recommendations:

> The "proper" way to do this would be to consume the Build Event Stream (https://bazel.build/remote/bep), which contains all command-line options in serialized form.

> A simpler approach that doesn't require running Bazel would be to parse the registry URLs out of the registryFileHashes URLs in the lockfile.

IMO we should go for the BEP since we are already running Bazel anyway.
Also from what he wrote, we should move away from the lock file anyway.

@haikoschol FYI

**Comment by haikoschol** [comment]
I agree that we should not rely on the lock file format.

But I'm not sure how we would use the BEP.

The `flags` property in the lock file recorded the CLI options that were used when the lock file was written. The assumption in the analyzer was that a custom registry used then would also be used for resolving dependencies of the project going forward.

The analyzer does run Bazel, but only to output the dependency graph, not to build the project. The Build Event Stream is emitted during a build. So in order to read the Build Event Stream to find out what flags were used, we need to run a build, which requires deciding what flags to use.

**Comment by nnobelis** [comment]
You are right regarding the BEP, and ORT does not do a full build, by design.

Then we will have unfortunately to stick with the `registryFileHashes` from the lock file unless you have another idea?

**Comment by haikoschol** [comment]
> Then we will have unfortunately to stick with the `registryFileHashes` from the lock file unless you have another idea?

Unfortunately not. So it looks like we have to rely on this implementation detail. Even worse, since `registryFileHashes` was only added recently, ORT ideally needs to support different versions of Bazel lock files explicitely (so much for that [being unlikely](https://github.com/oss-review-toolkit/ort/pull/8783#discussion_r1650318151)).
